package com.wyyuand.dao;

import com.wyyuand.domain.BabyWeight;
import com.wyyuand.domain.BabyWeightExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BabyWeightMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_baby_weight
     *
     * @mbg.generated Thu Jul 04 19:48:40 CST 2019
     */
    long countByExample(BabyWeightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_baby_weight
     *
     * @mbg.generated Thu Jul 04 19:48:40 CST 2019
     */
    int deleteByExample(BabyWeightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_baby_weight
     *
     * @mbg.generated Thu Jul 04 19:48:40 CST 2019
     */
    int deleteByPrimaryKey(String weightId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_baby_weight
     *
     * @mbg.generated Thu Jul 04 19:48:40 CST 2019
     */
    int insert(BabyWeight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_baby_weight
     *
     * @mbg.generated Thu Jul 04 19:48:40 CST 2019
     */
    int insertSelective(BabyWeight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_baby_weight
     *
     * @mbg.generated Thu Jul 04 19:48:40 CST 2019
     */
    List<BabyWeight> selectByExample(BabyWeightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_baby_weight
     *
     * @mbg.generated Thu Jul 04 19:48:40 CST 2019
     */
    BabyWeight selectByPrimaryKey(String weightId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_baby_weight
     *
     * @mbg.generated Thu Jul 04 19:48:40 CST 2019
     */
    int updateByExampleSelective(@Param("record") BabyWeight record, @Param("example") BabyWeightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_baby_weight
     *
     * @mbg.generated Thu Jul 04 19:48:40 CST 2019
     */
    int updateByExample(@Param("record") BabyWeight record, @Param("example") BabyWeightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_baby_weight
     *
     * @mbg.generated Thu Jul 04 19:48:40 CST 2019
     */
    int updateByPrimaryKeySelective(BabyWeight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_baby_weight
     *
     * @mbg.generated Thu Jul 04 19:48:40 CST 2019
     */
    int updateByPrimaryKey(BabyWeight record);
}