package com.wyyuand.dao;

import com.wyyuand.domain.CircleReply;
import com.wyyuand.domain.CircleReplyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CircleReplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_circle_reply
     *
     * @mbg.generated Tue Jul 09 15:01:41 CST 2019
     */
    long countByExample(CircleReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_circle_reply
     *
     * @mbg.generated Tue Jul 09 15:01:41 CST 2019
     */
    int deleteByExample(CircleReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_circle_reply
     *
     * @mbg.generated Tue Jul 09 15:01:41 CST 2019
     */
    int deleteByPrimaryKey(String replyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_circle_reply
     *
     * @mbg.generated Tue Jul 09 15:01:41 CST 2019
     */
    int insert(CircleReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_circle_reply
     *
     * @mbg.generated Tue Jul 09 15:01:41 CST 2019
     */
    int insertSelective(CircleReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_circle_reply
     *
     * @mbg.generated Tue Jul 09 15:01:41 CST 2019
     */
    List<CircleReply> selectByExample(CircleReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_circle_reply
     *
     * @mbg.generated Tue Jul 09 15:01:41 CST 2019
     */
    CircleReply selectByPrimaryKey(String replyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_circle_reply
     *
     * @mbg.generated Tue Jul 09 15:01:41 CST 2019
     */
    int updateByExampleSelective(@Param("record") CircleReply record, @Param("example") CircleReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_circle_reply
     *
     * @mbg.generated Tue Jul 09 15:01:41 CST 2019
     */
    int updateByExample(@Param("record") CircleReply record, @Param("example") CircleReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_circle_reply
     *
     * @mbg.generated Tue Jul 09 15:01:41 CST 2019
     */
    int updateByPrimaryKeySelective(CircleReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_circle_reply
     *
     * @mbg.generated Tue Jul 09 15:01:41 CST 2019
     */
    int updateByPrimaryKey(CircleReply record);
}