package com.wyyuand.dao;

import com.wyyuand.domain.Circle;
import com.wyyuand.domain.CircleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CircleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_circle
     *
     * @mbg.generated Tue Jul 09 22:35:00 CST 2019
     */
    long countByExample(CircleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_circle
     *
     * @mbg.generated Tue Jul 09 22:35:00 CST 2019
     */
    int deleteByExample(CircleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_circle
     *
     * @mbg.generated Tue Jul 09 22:35:00 CST 2019
     */
    int deleteByPrimaryKey(String circleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_circle
     *
     * @mbg.generated Tue Jul 09 22:35:00 CST 2019
     */
    int insert(Circle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_circle
     *
     * @mbg.generated Tue Jul 09 22:35:00 CST 2019
     */
    int insertSelective(Circle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_circle
     *
     * @mbg.generated Tue Jul 09 22:35:00 CST 2019
     */
    List<Circle> selectByExample(CircleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_circle
     *
     * @mbg.generated Tue Jul 09 22:35:00 CST 2019
     */
    Circle selectByPrimaryKey(String circleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_circle
     *
     * @mbg.generated Tue Jul 09 22:35:00 CST 2019
     */
    int updateByExampleSelective(@Param("record") Circle record, @Param("example") CircleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_circle
     *
     * @mbg.generated Tue Jul 09 22:35:00 CST 2019
     */
    int updateByExample(@Param("record") Circle record, @Param("example") CircleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_circle
     *
     * @mbg.generated Tue Jul 09 22:35:00 CST 2019
     */
    int updateByPrimaryKeySelective(Circle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_circle
     *
     * @mbg.generated Tue Jul 09 22:35:00 CST 2019
     */
    int updateByPrimaryKey(Circle record);
}