package com.wyyuand.dao;

import com.wyyuand.domain.Prestatus;
import com.wyyuand.domain.PrestatusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PrestatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_prestatus
     *
     * @mbg.generated Fri Jun 28 09:41:43 CST 2019
     */
    long countByExample(PrestatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_prestatus
     *
     * @mbg.generated Fri Jun 28 09:41:43 CST 2019
     */
    int deleteByExample(PrestatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_prestatus
     *
     * @mbg.generated Fri Jun 28 09:41:43 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_prestatus
     *
     * @mbg.generated Fri Jun 28 09:41:43 CST 2019
     */
    int insert(Prestatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_prestatus
     *
     * @mbg.generated Fri Jun 28 09:41:43 CST 2019
     */
    int insertSelective(Prestatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_prestatus
     *
     * @mbg.generated Fri Jun 28 09:41:43 CST 2019
     */
    List<Prestatus> selectByExample(PrestatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_prestatus
     *
     * @mbg.generated Fri Jun 28 09:41:43 CST 2019
     */
    Prestatus selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_prestatus
     *
     * @mbg.generated Fri Jun 28 09:41:43 CST 2019
     */
    int updateByExampleSelective(@Param("record") Prestatus record, @Param("example") PrestatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_prestatus
     *
     * @mbg.generated Fri Jun 28 09:41:43 CST 2019
     */
    int updateByExample(@Param("record") Prestatus record, @Param("example") PrestatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_prestatus
     *
     * @mbg.generated Fri Jun 28 09:41:43 CST 2019
     */
    int updateByPrimaryKeySelective(Prestatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_prestatus
     *
     * @mbg.generated Fri Jun 28 09:41:43 CST 2019
     */
    int updateByPrimaryKey(Prestatus record);
}