package com.wyyuand.dao;

import com.wyyuand.domain.PreTime;
import com.wyyuand.domain.PreTimeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PreTimeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pre_time
     *
     * @mbg.generated Wed Jul 03 10:07:01 CST 2019
     */
    long countByExample(PreTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pre_time
     *
     * @mbg.generated Wed Jul 03 10:07:01 CST 2019
     */
    int deleteByExample(PreTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pre_time
     *
     * @mbg.generated Wed Jul 03 10:07:01 CST 2019
     */
    int deleteByPrimaryKey(String checkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pre_time
     *
     * @mbg.generated Wed Jul 03 10:07:01 CST 2019
     */
    int insert(PreTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pre_time
     *
     * @mbg.generated Wed Jul 03 10:07:01 CST 2019
     */
    int insertSelective(PreTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pre_time
     *
     * @mbg.generated Wed Jul 03 10:07:01 CST 2019
     */
    List<PreTime> selectByExample(PreTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pre_time
     *
     * @mbg.generated Wed Jul 03 10:07:01 CST 2019
     */
    PreTime selectByPrimaryKey(String checkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pre_time
     *
     * @mbg.generated Wed Jul 03 10:07:01 CST 2019
     */
    int updateByExampleSelective(@Param("record") PreTime record, @Param("example") PreTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pre_time
     *
     * @mbg.generated Wed Jul 03 10:07:01 CST 2019
     */
    int updateByExample(@Param("record") PreTime record, @Param("example") PreTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pre_time
     *
     * @mbg.generated Wed Jul 03 10:07:01 CST 2019
     */
    int updateByPrimaryKeySelective(PreTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pre_time
     *
     * @mbg.generated Wed Jul 03 10:07:01 CST 2019
     */
    int updateByPrimaryKey(PreTime record);
}