package com.wyyuand.domain;

import java.util.Date;

public class Admin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.adm_id
     *
     * @mbg.generated Fri May 17 09:52:00 CST 2019
     */
    private String admId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.adm_name
     *
     * @mbg.generated Fri May 17 09:52:00 CST 2019
     */
    private String admName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.adm_display_name
     *
     * @mbg.generated Fri May 17 09:52:00 CST 2019
     */
    private String admDisplayName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.adm_sex
     *
     * @mbg.generated Fri May 17 09:52:00 CST 2019
     */
    private String admSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.adm_password
     *
     * @mbg.generated Fri May 17 09:52:00 CST 2019
     */
    private String admPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.adm_create_time
     *
     * @mbg.generated Fri May 17 09:52:00 CST 2019
     */
    private Date admCreateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.adm_exp_date
     *
     * @mbg.generated Fri May 17 09:52:00 CST 2019
     */
    private Date admExpDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.adm_email
     *
     * @mbg.generated Fri May 17 09:52:00 CST 2019
     */
    private String admEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.adm_status
     *
     * @mbg.generated Fri May 17 09:52:00 CST 2019
     */
    private String admStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.adm_id
     *
     * @return the value of t_admin.adm_id
     *
     * @mbg.generated Fri May 17 09:52:00 CST 2019
     */
    public String getAdmId() {
        return admId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.adm_id
     *
     * @param admId the value for t_admin.adm_id
     *
     * @mbg.generated Fri May 17 09:52:00 CST 2019
     */
    public void setAdmId(String admId) {
        this.admId = admId == null ? null : admId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.adm_name
     *
     * @return the value of t_admin.adm_name
     *
     * @mbg.generated Fri May 17 09:52:00 CST 2019
     */
    public String getAdmName() {
        return admName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.adm_name
     *
     * @param admName the value for t_admin.adm_name
     *
     * @mbg.generated Fri May 17 09:52:00 CST 2019
     */
    public void setAdmName(String admName) {
        this.admName = admName == null ? null : admName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.adm_display_name
     *
     * @return the value of t_admin.adm_display_name
     *
     * @mbg.generated Fri May 17 09:52:00 CST 2019
     */
    public String getAdmDisplayName() {
        return admDisplayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.adm_display_name
     *
     * @param admDisplayName the value for t_admin.adm_display_name
     *
     * @mbg.generated Fri May 17 09:52:00 CST 2019
     */
    public void setAdmDisplayName(String admDisplayName) {
        this.admDisplayName = admDisplayName == null ? null : admDisplayName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.adm_sex
     *
     * @return the value of t_admin.adm_sex
     *
     * @mbg.generated Fri May 17 09:52:00 CST 2019
     */
    public String getAdmSex() {
        return admSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.adm_sex
     *
     * @param admSex the value for t_admin.adm_sex
     *
     * @mbg.generated Fri May 17 09:52:00 CST 2019
     */
    public void setAdmSex(String admSex) {
        this.admSex = admSex == null ? null : admSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.adm_password
     *
     * @return the value of t_admin.adm_password
     *
     * @mbg.generated Fri May 17 09:52:00 CST 2019
     */
    public String getAdmPassword() {
        return admPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.adm_password
     *
     * @param admPassword the value for t_admin.adm_password
     *
     * @mbg.generated Fri May 17 09:52:00 CST 2019
     */
    public void setAdmPassword(String admPassword) {
        this.admPassword = admPassword == null ? null : admPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.adm_create_time
     *
     * @return the value of t_admin.adm_create_time
     *
     * @mbg.generated Fri May 17 09:52:00 CST 2019
     */
    public Date getAdmCreateTime() {
        return admCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.adm_create_time
     *
     * @param admCreateTime the value for t_admin.adm_create_time
     *
     * @mbg.generated Fri May 17 09:52:00 CST 2019
     */
    public void setAdmCreateTime(Date admCreateTime) {
        this.admCreateTime = admCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.adm_exp_date
     *
     * @return the value of t_admin.adm_exp_date
     *
     * @mbg.generated Fri May 17 09:52:00 CST 2019
     */
    public Date getAdmExpDate() {
        return admExpDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.adm_exp_date
     *
     * @param admExpDate the value for t_admin.adm_exp_date
     *
     * @mbg.generated Fri May 17 09:52:00 CST 2019
     */
    public void setAdmExpDate(Date admExpDate) {
        this.admExpDate = admExpDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.adm_email
     *
     * @return the value of t_admin.adm_email
     *
     * @mbg.generated Fri May 17 09:52:00 CST 2019
     */
    public String getAdmEmail() {
        return admEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.adm_email
     *
     * @param admEmail the value for t_admin.adm_email
     *
     * @mbg.generated Fri May 17 09:52:00 CST 2019
     */
    public void setAdmEmail(String admEmail) {
        this.admEmail = admEmail == null ? null : admEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.adm_status
     *
     * @return the value of t_admin.adm_status
     *
     * @mbg.generated Fri May 17 09:52:00 CST 2019
     */
    public String getAdmStatus() {
        return admStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.adm_status
     *
     * @param admStatus the value for t_admin.adm_status
     *
     * @mbg.generated Fri May 17 09:52:00 CST 2019
     */
    public void setAdmStatus(String admStatus) {
        this.admStatus = admStatus == null ? null : admStatus.trim();
    }
}