package com.wyyuand.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AdminExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_admin
     *
     * @mbg.generated Fri May 17 09:52:00 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_admin
     *
     * @mbg.generated Fri May 17 09:52:00 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_admin
     *
     * @mbg.generated Fri May 17 09:52:00 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbg.generated Fri May 17 09:52:00 CST 2019
     */
    public AdminExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbg.generated Fri May 17 09:52:00 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbg.generated Fri May 17 09:52:00 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbg.generated Fri May 17 09:52:00 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbg.generated Fri May 17 09:52:00 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbg.generated Fri May 17 09:52:00 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbg.generated Fri May 17 09:52:00 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbg.generated Fri May 17 09:52:00 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbg.generated Fri May 17 09:52:00 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbg.generated Fri May 17 09:52:00 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbg.generated Fri May 17 09:52:00 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_admin
     *
     * @mbg.generated Fri May 17 09:52:00 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAdmIdIsNull() {
            addCriterion("adm_id is null");
            return (Criteria) this;
        }

        public Criteria andAdmIdIsNotNull() {
            addCriterion("adm_id is not null");
            return (Criteria) this;
        }

        public Criteria andAdmIdEqualTo(String value) {
            addCriterion("adm_id =", value, "admId");
            return (Criteria) this;
        }

        public Criteria andAdmIdNotEqualTo(String value) {
            addCriterion("adm_id <>", value, "admId");
            return (Criteria) this;
        }

        public Criteria andAdmIdGreaterThan(String value) {
            addCriterion("adm_id >", value, "admId");
            return (Criteria) this;
        }

        public Criteria andAdmIdGreaterThanOrEqualTo(String value) {
            addCriterion("adm_id >=", value, "admId");
            return (Criteria) this;
        }

        public Criteria andAdmIdLessThan(String value) {
            addCriterion("adm_id <", value, "admId");
            return (Criteria) this;
        }

        public Criteria andAdmIdLessThanOrEqualTo(String value) {
            addCriterion("adm_id <=", value, "admId");
            return (Criteria) this;
        }

        public Criteria andAdmIdLike(String value) {
            addCriterion("adm_id like", value, "admId");
            return (Criteria) this;
        }

        public Criteria andAdmIdNotLike(String value) {
            addCriterion("adm_id not like", value, "admId");
            return (Criteria) this;
        }

        public Criteria andAdmIdIn(List<String> values) {
            addCriterion("adm_id in", values, "admId");
            return (Criteria) this;
        }

        public Criteria andAdmIdNotIn(List<String> values) {
            addCriterion("adm_id not in", values, "admId");
            return (Criteria) this;
        }

        public Criteria andAdmIdBetween(String value1, String value2) {
            addCriterion("adm_id between", value1, value2, "admId");
            return (Criteria) this;
        }

        public Criteria andAdmIdNotBetween(String value1, String value2) {
            addCriterion("adm_id not between", value1, value2, "admId");
            return (Criteria) this;
        }

        public Criteria andAdmNameIsNull() {
            addCriterion("adm_name is null");
            return (Criteria) this;
        }

        public Criteria andAdmNameIsNotNull() {
            addCriterion("adm_name is not null");
            return (Criteria) this;
        }

        public Criteria andAdmNameEqualTo(String value) {
            addCriterion("adm_name =", value, "admName");
            return (Criteria) this;
        }

        public Criteria andAdmNameNotEqualTo(String value) {
            addCriterion("adm_name <>", value, "admName");
            return (Criteria) this;
        }

        public Criteria andAdmNameGreaterThan(String value) {
            addCriterion("adm_name >", value, "admName");
            return (Criteria) this;
        }

        public Criteria andAdmNameGreaterThanOrEqualTo(String value) {
            addCriterion("adm_name >=", value, "admName");
            return (Criteria) this;
        }

        public Criteria andAdmNameLessThan(String value) {
            addCriterion("adm_name <", value, "admName");
            return (Criteria) this;
        }

        public Criteria andAdmNameLessThanOrEqualTo(String value) {
            addCriterion("adm_name <=", value, "admName");
            return (Criteria) this;
        }

        public Criteria andAdmNameLike(String value) {
            addCriterion("adm_name like", value, "admName");
            return (Criteria) this;
        }

        public Criteria andAdmNameNotLike(String value) {
            addCriterion("adm_name not like", value, "admName");
            return (Criteria) this;
        }

        public Criteria andAdmNameIn(List<String> values) {
            addCriterion("adm_name in", values, "admName");
            return (Criteria) this;
        }

        public Criteria andAdmNameNotIn(List<String> values) {
            addCriterion("adm_name not in", values, "admName");
            return (Criteria) this;
        }

        public Criteria andAdmNameBetween(String value1, String value2) {
            addCriterion("adm_name between", value1, value2, "admName");
            return (Criteria) this;
        }

        public Criteria andAdmNameNotBetween(String value1, String value2) {
            addCriterion("adm_name not between", value1, value2, "admName");
            return (Criteria) this;
        }

        public Criteria andAdmDisplayNameIsNull() {
            addCriterion("adm_display_name is null");
            return (Criteria) this;
        }

        public Criteria andAdmDisplayNameIsNotNull() {
            addCriterion("adm_display_name is not null");
            return (Criteria) this;
        }

        public Criteria andAdmDisplayNameEqualTo(String value) {
            addCriterion("adm_display_name =", value, "admDisplayName");
            return (Criteria) this;
        }

        public Criteria andAdmDisplayNameNotEqualTo(String value) {
            addCriterion("adm_display_name <>", value, "admDisplayName");
            return (Criteria) this;
        }

        public Criteria andAdmDisplayNameGreaterThan(String value) {
            addCriterion("adm_display_name >", value, "admDisplayName");
            return (Criteria) this;
        }

        public Criteria andAdmDisplayNameGreaterThanOrEqualTo(String value) {
            addCriterion("adm_display_name >=", value, "admDisplayName");
            return (Criteria) this;
        }

        public Criteria andAdmDisplayNameLessThan(String value) {
            addCriterion("adm_display_name <", value, "admDisplayName");
            return (Criteria) this;
        }

        public Criteria andAdmDisplayNameLessThanOrEqualTo(String value) {
            addCriterion("adm_display_name <=", value, "admDisplayName");
            return (Criteria) this;
        }

        public Criteria andAdmDisplayNameLike(String value) {
            addCriterion("adm_display_name like", value, "admDisplayName");
            return (Criteria) this;
        }

        public Criteria andAdmDisplayNameNotLike(String value) {
            addCriterion("adm_display_name not like", value, "admDisplayName");
            return (Criteria) this;
        }

        public Criteria andAdmDisplayNameIn(List<String> values) {
            addCriterion("adm_display_name in", values, "admDisplayName");
            return (Criteria) this;
        }

        public Criteria andAdmDisplayNameNotIn(List<String> values) {
            addCriterion("adm_display_name not in", values, "admDisplayName");
            return (Criteria) this;
        }

        public Criteria andAdmDisplayNameBetween(String value1, String value2) {
            addCriterion("adm_display_name between", value1, value2, "admDisplayName");
            return (Criteria) this;
        }

        public Criteria andAdmDisplayNameNotBetween(String value1, String value2) {
            addCriterion("adm_display_name not between", value1, value2, "admDisplayName");
            return (Criteria) this;
        }

        public Criteria andAdmSexIsNull() {
            addCriterion("adm_sex is null");
            return (Criteria) this;
        }

        public Criteria andAdmSexIsNotNull() {
            addCriterion("adm_sex is not null");
            return (Criteria) this;
        }

        public Criteria andAdmSexEqualTo(String value) {
            addCriterion("adm_sex =", value, "admSex");
            return (Criteria) this;
        }

        public Criteria andAdmSexNotEqualTo(String value) {
            addCriterion("adm_sex <>", value, "admSex");
            return (Criteria) this;
        }

        public Criteria andAdmSexGreaterThan(String value) {
            addCriterion("adm_sex >", value, "admSex");
            return (Criteria) this;
        }

        public Criteria andAdmSexGreaterThanOrEqualTo(String value) {
            addCriterion("adm_sex >=", value, "admSex");
            return (Criteria) this;
        }

        public Criteria andAdmSexLessThan(String value) {
            addCriterion("adm_sex <", value, "admSex");
            return (Criteria) this;
        }

        public Criteria andAdmSexLessThanOrEqualTo(String value) {
            addCriterion("adm_sex <=", value, "admSex");
            return (Criteria) this;
        }

        public Criteria andAdmSexLike(String value) {
            addCriterion("adm_sex like", value, "admSex");
            return (Criteria) this;
        }

        public Criteria andAdmSexNotLike(String value) {
            addCriterion("adm_sex not like", value, "admSex");
            return (Criteria) this;
        }

        public Criteria andAdmSexIn(List<String> values) {
            addCriterion("adm_sex in", values, "admSex");
            return (Criteria) this;
        }

        public Criteria andAdmSexNotIn(List<String> values) {
            addCriterion("adm_sex not in", values, "admSex");
            return (Criteria) this;
        }

        public Criteria andAdmSexBetween(String value1, String value2) {
            addCriterion("adm_sex between", value1, value2, "admSex");
            return (Criteria) this;
        }

        public Criteria andAdmSexNotBetween(String value1, String value2) {
            addCriterion("adm_sex not between", value1, value2, "admSex");
            return (Criteria) this;
        }

        public Criteria andAdmPasswordIsNull() {
            addCriterion("adm_password is null");
            return (Criteria) this;
        }

        public Criteria andAdmPasswordIsNotNull() {
            addCriterion("adm_password is not null");
            return (Criteria) this;
        }

        public Criteria andAdmPasswordEqualTo(String value) {
            addCriterion("adm_password =", value, "admPassword");
            return (Criteria) this;
        }

        public Criteria andAdmPasswordNotEqualTo(String value) {
            addCriterion("adm_password <>", value, "admPassword");
            return (Criteria) this;
        }

        public Criteria andAdmPasswordGreaterThan(String value) {
            addCriterion("adm_password >", value, "admPassword");
            return (Criteria) this;
        }

        public Criteria andAdmPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("adm_password >=", value, "admPassword");
            return (Criteria) this;
        }

        public Criteria andAdmPasswordLessThan(String value) {
            addCriterion("adm_password <", value, "admPassword");
            return (Criteria) this;
        }

        public Criteria andAdmPasswordLessThanOrEqualTo(String value) {
            addCriterion("adm_password <=", value, "admPassword");
            return (Criteria) this;
        }

        public Criteria andAdmPasswordLike(String value) {
            addCriterion("adm_password like", value, "admPassword");
            return (Criteria) this;
        }

        public Criteria andAdmPasswordNotLike(String value) {
            addCriterion("adm_password not like", value, "admPassword");
            return (Criteria) this;
        }

        public Criteria andAdmPasswordIn(List<String> values) {
            addCriterion("adm_password in", values, "admPassword");
            return (Criteria) this;
        }

        public Criteria andAdmPasswordNotIn(List<String> values) {
            addCriterion("adm_password not in", values, "admPassword");
            return (Criteria) this;
        }

        public Criteria andAdmPasswordBetween(String value1, String value2) {
            addCriterion("adm_password between", value1, value2, "admPassword");
            return (Criteria) this;
        }

        public Criteria andAdmPasswordNotBetween(String value1, String value2) {
            addCriterion("adm_password not between", value1, value2, "admPassword");
            return (Criteria) this;
        }

        public Criteria andAdmCreateTimeIsNull() {
            addCriterion("adm_create_time is null");
            return (Criteria) this;
        }

        public Criteria andAdmCreateTimeIsNotNull() {
            addCriterion("adm_create_time is not null");
            return (Criteria) this;
        }

        public Criteria andAdmCreateTimeEqualTo(Date value) {
            addCriterion("adm_create_time =", value, "admCreateTime");
            return (Criteria) this;
        }

        public Criteria andAdmCreateTimeNotEqualTo(Date value) {
            addCriterion("adm_create_time <>", value, "admCreateTime");
            return (Criteria) this;
        }

        public Criteria andAdmCreateTimeGreaterThan(Date value) {
            addCriterion("adm_create_time >", value, "admCreateTime");
            return (Criteria) this;
        }

        public Criteria andAdmCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("adm_create_time >=", value, "admCreateTime");
            return (Criteria) this;
        }

        public Criteria andAdmCreateTimeLessThan(Date value) {
            addCriterion("adm_create_time <", value, "admCreateTime");
            return (Criteria) this;
        }

        public Criteria andAdmCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("adm_create_time <=", value, "admCreateTime");
            return (Criteria) this;
        }

        public Criteria andAdmCreateTimeIn(List<Date> values) {
            addCriterion("adm_create_time in", values, "admCreateTime");
            return (Criteria) this;
        }

        public Criteria andAdmCreateTimeNotIn(List<Date> values) {
            addCriterion("adm_create_time not in", values, "admCreateTime");
            return (Criteria) this;
        }

        public Criteria andAdmCreateTimeBetween(Date value1, Date value2) {
            addCriterion("adm_create_time between", value1, value2, "admCreateTime");
            return (Criteria) this;
        }

        public Criteria andAdmCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("adm_create_time not between", value1, value2, "admCreateTime");
            return (Criteria) this;
        }

        public Criteria andAdmExpDateIsNull() {
            addCriterion("adm_exp_date is null");
            return (Criteria) this;
        }

        public Criteria andAdmExpDateIsNotNull() {
            addCriterion("adm_exp_date is not null");
            return (Criteria) this;
        }

        public Criteria andAdmExpDateEqualTo(Date value) {
            addCriterion("adm_exp_date =", value, "admExpDate");
            return (Criteria) this;
        }

        public Criteria andAdmExpDateNotEqualTo(Date value) {
            addCriterion("adm_exp_date <>", value, "admExpDate");
            return (Criteria) this;
        }

        public Criteria andAdmExpDateGreaterThan(Date value) {
            addCriterion("adm_exp_date >", value, "admExpDate");
            return (Criteria) this;
        }

        public Criteria andAdmExpDateGreaterThanOrEqualTo(Date value) {
            addCriterion("adm_exp_date >=", value, "admExpDate");
            return (Criteria) this;
        }

        public Criteria andAdmExpDateLessThan(Date value) {
            addCriterion("adm_exp_date <", value, "admExpDate");
            return (Criteria) this;
        }

        public Criteria andAdmExpDateLessThanOrEqualTo(Date value) {
            addCriterion("adm_exp_date <=", value, "admExpDate");
            return (Criteria) this;
        }

        public Criteria andAdmExpDateIn(List<Date> values) {
            addCriterion("adm_exp_date in", values, "admExpDate");
            return (Criteria) this;
        }

        public Criteria andAdmExpDateNotIn(List<Date> values) {
            addCriterion("adm_exp_date not in", values, "admExpDate");
            return (Criteria) this;
        }

        public Criteria andAdmExpDateBetween(Date value1, Date value2) {
            addCriterion("adm_exp_date between", value1, value2, "admExpDate");
            return (Criteria) this;
        }

        public Criteria andAdmExpDateNotBetween(Date value1, Date value2) {
            addCriterion("adm_exp_date not between", value1, value2, "admExpDate");
            return (Criteria) this;
        }

        public Criteria andAdmEmailIsNull() {
            addCriterion("adm_email is null");
            return (Criteria) this;
        }

        public Criteria andAdmEmailIsNotNull() {
            addCriterion("adm_email is not null");
            return (Criteria) this;
        }

        public Criteria andAdmEmailEqualTo(String value) {
            addCriterion("adm_email =", value, "admEmail");
            return (Criteria) this;
        }

        public Criteria andAdmEmailNotEqualTo(String value) {
            addCriterion("adm_email <>", value, "admEmail");
            return (Criteria) this;
        }

        public Criteria andAdmEmailGreaterThan(String value) {
            addCriterion("adm_email >", value, "admEmail");
            return (Criteria) this;
        }

        public Criteria andAdmEmailGreaterThanOrEqualTo(String value) {
            addCriterion("adm_email >=", value, "admEmail");
            return (Criteria) this;
        }

        public Criteria andAdmEmailLessThan(String value) {
            addCriterion("adm_email <", value, "admEmail");
            return (Criteria) this;
        }

        public Criteria andAdmEmailLessThanOrEqualTo(String value) {
            addCriterion("adm_email <=", value, "admEmail");
            return (Criteria) this;
        }

        public Criteria andAdmEmailLike(String value) {
            addCriterion("adm_email like", value, "admEmail");
            return (Criteria) this;
        }

        public Criteria andAdmEmailNotLike(String value) {
            addCriterion("adm_email not like", value, "admEmail");
            return (Criteria) this;
        }

        public Criteria andAdmEmailIn(List<String> values) {
            addCriterion("adm_email in", values, "admEmail");
            return (Criteria) this;
        }

        public Criteria andAdmEmailNotIn(List<String> values) {
            addCriterion("adm_email not in", values, "admEmail");
            return (Criteria) this;
        }

        public Criteria andAdmEmailBetween(String value1, String value2) {
            addCriterion("adm_email between", value1, value2, "admEmail");
            return (Criteria) this;
        }

        public Criteria andAdmEmailNotBetween(String value1, String value2) {
            addCriterion("adm_email not between", value1, value2, "admEmail");
            return (Criteria) this;
        }

        public Criteria andAdmStatusIsNull() {
            addCriterion("adm_status is null");
            return (Criteria) this;
        }

        public Criteria andAdmStatusIsNotNull() {
            addCriterion("adm_status is not null");
            return (Criteria) this;
        }

        public Criteria andAdmStatusEqualTo(String value) {
            addCriterion("adm_status =", value, "admStatus");
            return (Criteria) this;
        }

        public Criteria andAdmStatusNotEqualTo(String value) {
            addCriterion("adm_status <>", value, "admStatus");
            return (Criteria) this;
        }

        public Criteria andAdmStatusGreaterThan(String value) {
            addCriterion("adm_status >", value, "admStatus");
            return (Criteria) this;
        }

        public Criteria andAdmStatusGreaterThanOrEqualTo(String value) {
            addCriterion("adm_status >=", value, "admStatus");
            return (Criteria) this;
        }

        public Criteria andAdmStatusLessThan(String value) {
            addCriterion("adm_status <", value, "admStatus");
            return (Criteria) this;
        }

        public Criteria andAdmStatusLessThanOrEqualTo(String value) {
            addCriterion("adm_status <=", value, "admStatus");
            return (Criteria) this;
        }

        public Criteria andAdmStatusLike(String value) {
            addCriterion("adm_status like", value, "admStatus");
            return (Criteria) this;
        }

        public Criteria andAdmStatusNotLike(String value) {
            addCriterion("adm_status not like", value, "admStatus");
            return (Criteria) this;
        }

        public Criteria andAdmStatusIn(List<String> values) {
            addCriterion("adm_status in", values, "admStatus");
            return (Criteria) this;
        }

        public Criteria andAdmStatusNotIn(List<String> values) {
            addCriterion("adm_status not in", values, "admStatus");
            return (Criteria) this;
        }

        public Criteria andAdmStatusBetween(String value1, String value2) {
            addCriterion("adm_status between", value1, value2, "admStatus");
            return (Criteria) this;
        }

        public Criteria andAdmStatusNotBetween(String value1, String value2) {
            addCriterion("adm_status not between", value1, value2, "admStatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_admin
     *
     * @mbg.generated do_not_delete_during_merge Fri May 17 09:52:00 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_admin
     *
     * @mbg.generated Fri May 17 09:52:00 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}