package com.wyyuand.domain;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.math.BigDecimal;
import java.util.Date;

public class BabyWeight {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_baby_weight.weight_id
     *
     * @mbg.generated Thu Jul 04 19:48:40 CST 2019
     */
    private String weightId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_baby_weight.user_id
     *
     * @mbg.generated Thu Jul 04 19:48:40 CST 2019
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_baby_weight.weight_data
     *
     * @mbg.generated Thu Jul 04 19:48:40 CST 2019
     */
    private Date weightData;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_baby_weight.bdp
     *
     * @mbg.generated Thu Jul 04 19:48:40 CST 2019
     */
    private BigDecimal bdp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_baby_weight.ac
     *
     * @mbg.generated Thu Jul 04 19:48:40 CST 2019
     */
    private BigDecimal ac;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_baby_weight.fl
     *
     * @mbg.generated Thu Jul 04 19:48:40 CST 2019
     */
    private BigDecimal fl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_baby_weight.weight_value
     *
     * @mbg.generated Thu Jul 04 19:48:40 CST 2019
     */
    private BigDecimal weightValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_baby_weight.weight_id
     *
     * @return the value of t_baby_weight.weight_id
     *
     * @mbg.generated Thu Jul 04 19:48:40 CST 2019
     */
    public String getWeightId() {
        return weightId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_baby_weight.weight_id
     *
     * @param weightId the value for t_baby_weight.weight_id
     *
     * @mbg.generated Thu Jul 04 19:48:40 CST 2019
     */
    public void setWeightId(String weightId) {
        this.weightId = weightId == null ? null : weightId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_baby_weight.user_id
     *
     * @return the value of t_baby_weight.user_id
     *
     * @mbg.generated Thu Jul 04 19:48:40 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_baby_weight.user_id
     *
     * @param userId the value for t_baby_weight.user_id
     *
     * @mbg.generated Thu Jul 04 19:48:40 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_baby_weight.weight_data
     *
     * @return the value of t_baby_weight.weight_data
     *
     * @mbg.generated Thu Jul 04 19:48:40 CST 2019
     */

    @DateTimeFormat(pattern="yyyy-MM-dd")
    @JsonFormat(pattern="yyyy-MM-dd",timezone = "GMT+8")
    public Date getWeightData() {
        return weightData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_baby_weight.weight_data
     *
     * @param weightData the value for t_baby_weight.weight_data
     *
     * @mbg.generated Thu Jul 04 19:48:40 CST 2019
     */
    public void setWeightData(Date weightData) {
        this.weightData = weightData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_baby_weight.bdp
     *
     * @return the value of t_baby_weight.bdp
     *
     * @mbg.generated Thu Jul 04 19:48:40 CST 2019
     */
    public BigDecimal getBdp() {
        return bdp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_baby_weight.bdp
     *
     * @param bdp the value for t_baby_weight.bdp
     *
     * @mbg.generated Thu Jul 04 19:48:40 CST 2019
     */
    public void setBdp(BigDecimal bdp) {
        this.bdp = bdp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_baby_weight.ac
     *
     * @return the value of t_baby_weight.ac
     *
     * @mbg.generated Thu Jul 04 19:48:40 CST 2019
     */
    public BigDecimal getAc() {
        return ac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_baby_weight.ac
     *
     * @param ac the value for t_baby_weight.ac
     *
     * @mbg.generated Thu Jul 04 19:48:40 CST 2019
     */
    public void setAc(BigDecimal ac) {
        this.ac = ac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_baby_weight.fl
     *
     * @return the value of t_baby_weight.fl
     *
     * @mbg.generated Thu Jul 04 19:48:40 CST 2019
     */
    public BigDecimal getFl() {
        return fl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_baby_weight.fl
     *
     * @param fl the value for t_baby_weight.fl
     *
     * @mbg.generated Thu Jul 04 19:48:40 CST 2019
     */
    public void setFl(BigDecimal fl) {
        this.fl = fl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_baby_weight.weight_value
     *
     * @return the value of t_baby_weight.weight_value
     *
     * @mbg.generated Thu Jul 04 19:48:40 CST 2019
     */
    public BigDecimal getWeightValue() {
        return weightValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_baby_weight.weight_value
     *
     * @param weightValue the value for t_baby_weight.weight_value
     *
     * @mbg.generated Thu Jul 04 19:48:40 CST 2019
     */
    public void setWeightValue(BigDecimal weightValue) {
        this.weightValue = weightValue;
    }
}