package com.wyyuand.domain;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class Circle {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_circle.circle_id
     *
     * @mbg.generated Tue Jul 09 22:35:00 CST 2019
     */
    private String circleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_circle.user_id
     *
     * @mbg.generated Tue Jul 09 22:35:00 CST 2019
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_circle.circle_theme
     *
     * @mbg.generated Tue Jul 09 22:35:00 CST 2019
     */
    private String circleTheme;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_circle.circle_content
     *
     * @mbg.generated Tue Jul 09 22:35:00 CST 2019
     */
    private String circleContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_circle.circle_public_time
     *
     * @mbg.generated Tue Jul 09 22:35:00 CST 2019
     */
    private Date circlePublicTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_circle.fllow_num
     *
     * @mbg.generated Tue Jul 09 22:35:00 CST 2019
     */
    private Integer fllowNum;

    private User user;

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_circle.circle_id
     *
     * @return the value of t_circle.circle_id
     *
     * @mbg.generated Tue Jul 09 22:35:00 CST 2019
     */
    public String getCircleId() {
        return circleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_circle.circle_id
     *
     * @param circleId the value for t_circle.circle_id
     *
     * @mbg.generated Tue Jul 09 22:35:00 CST 2019
     */
    public void setCircleId(String circleId) {
        this.circleId = circleId == null ? null : circleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_circle.user_id
     *
     * @return the value of t_circle.user_id
     *
     * @mbg.generated Tue Jul 09 22:35:00 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_circle.user_id
     *
     * @param userId the value for t_circle.user_id
     *
     * @mbg.generated Tue Jul 09 22:35:00 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_circle.circle_theme
     *
     * @return the value of t_circle.circle_theme
     *
     * @mbg.generated Tue Jul 09 22:35:00 CST 2019
     */
    public String getCircleTheme() {
        return circleTheme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_circle.circle_theme
     *
     * @param circleTheme the value for t_circle.circle_theme
     *
     * @mbg.generated Tue Jul 09 22:35:00 CST 2019
     */
    public void setCircleTheme(String circleTheme) {
        this.circleTheme = circleTheme == null ? null : circleTheme.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_circle.circle_content
     *
     * @return the value of t_circle.circle_content
     *
     * @mbg.generated Tue Jul 09 22:35:00 CST 2019
     */
    public String getCircleContent() {
        return circleContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_circle.circle_content
     *
     * @param circleContent the value for t_circle.circle_content
     *
     * @mbg.generated Tue Jul 09 22:35:00 CST 2019
     */
    public void setCircleContent(String circleContent) {
        this.circleContent = circleContent == null ? null : circleContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_circle.circle_public_time
     *
     * @return the value of t_circle.circle_public_time
     *
     * @mbg.generated Tue Jul 09 22:35:00 CST 2019
     */
    @DateTimeFormat(pattern="yyyy-MM-dd HH:mm")
    @JsonFormat(pattern="yyyy-MM-dd HH:mm",timezone = "GMT+8")
    public Date getCirclePublicTime() {
        return circlePublicTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_circle.circle_public_time
     *
     * @param circlePublicTime the value for t_circle.circle_public_time
     *
     * @mbg.generated Tue Jul 09 22:35:00 CST 2019
     */
    public void setCirclePublicTime(Date circlePublicTime) {
        this.circlePublicTime = circlePublicTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_circle.fllow_num
     *
     * @return the value of t_circle.fllow_num
     *
     * @mbg.generated Tue Jul 09 22:35:00 CST 2019
     */
    public Integer getFllowNum() {
        return fllowNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_circle.fllow_num
     *
     * @param fllowNum the value for t_circle.fllow_num
     *
     * @mbg.generated Tue Jul 09 22:35:00 CST 2019
     */
    public void setFllowNum(Integer fllowNum) {
        this.fllowNum = fllowNum;
    }
}