package com.wyyuand.domain;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;
import java.util.List;

public class CircleComment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_circle_comment.id
     *
     * @mbg.generated Tue Jul 09 14:22:52 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_circle_comment.circle_id
     *
     * @mbg.generated Tue Jul 09 14:22:52 CST 2019
     */
    private String circleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_circle_comment.user_id
     *
     * @mbg.generated Tue Jul 09 14:22:52 CST 2019
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_circle_comment.nick_name
     *
     * @mbg.generated Tue Jul 09 14:22:52 CST 2019
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_circle_comment.user_logo
     *
     * @mbg.generated Tue Jul 09 14:22:52 CST 2019
     */
    private String userLogo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_circle_comment.content
     *
     * @mbg.generated Tue Jul 09 14:22:52 CST 2019
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_circle_comment.reply_total
     *
     * @mbg.generated Tue Jul 09 14:22:52 CST 2019
     */
    private Integer replyTotal;

    private User user;

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_circle_comment.create_date
     *
     * @mbg.generated Tue Jul 09 14:22:52 CST 2019
     */
    private Date createDate;

    private  List<CircleReply> replyList;

    public List<CircleReply> getReplyList() {
        return replyList;
    }

    public void setReplyList(List<CircleReply> replyList) {
        this.replyList = replyList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_circle_comment.id
     *
     * @return the value of t_circle_comment.id
     *
     * @mbg.generated Tue Jul 09 14:22:52 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_circle_comment.id
     *
     * @param id the value for t_circle_comment.id
     *
     * @mbg.generated Tue Jul 09 14:22:52 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_circle_comment.circle_id
     *
     * @return the value of t_circle_comment.circle_id
     *
     * @mbg.generated Tue Jul 09 14:22:52 CST 2019
     */
    public String getCircleId() {
        return circleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_circle_comment.circle_id
     *
     * @param circleId the value for t_circle_comment.circle_id
     *
     * @mbg.generated Tue Jul 09 14:22:52 CST 2019
     */
    public void setCircleId(String circleId) {
        this.circleId = circleId == null ? null : circleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_circle_comment.user_id
     *
     * @return the value of t_circle_comment.user_id
     *
     * @mbg.generated Tue Jul 09 14:22:52 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_circle_comment.user_id
     *
     * @param userId the value for t_circle_comment.user_id
     *
     * @mbg.generated Tue Jul 09 14:22:52 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_circle_comment.nick_name
     *
     * @return the value of t_circle_comment.nick_name
     *
     * @mbg.generated Tue Jul 09 14:22:52 CST 2019
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_circle_comment.nick_name
     *
     * @param nickName the value for t_circle_comment.nick_name
     *
     * @mbg.generated Tue Jul 09 14:22:52 CST 2019
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_circle_comment.user_logo
     *
     * @return the value of t_circle_comment.user_logo
     *
     * @mbg.generated Tue Jul 09 14:22:52 CST 2019
     */
    public String getUserLogo() {
        return userLogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_circle_comment.user_logo
     *
     * @param userLogo the value for t_circle_comment.user_logo
     *
     * @mbg.generated Tue Jul 09 14:22:52 CST 2019
     */
    public void setUserLogo(String userLogo) {
        this.userLogo = userLogo == null ? null : userLogo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_circle_comment.content
     *
     * @return the value of t_circle_comment.content
     *
     * @mbg.generated Tue Jul 09 14:22:52 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_circle_comment.content
     *
     * @param content the value for t_circle_comment.content
     *
     * @mbg.generated Tue Jul 09 14:22:52 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_circle_comment.reply_total
     *
     * @return the value of t_circle_comment.reply_total
     *
     * @mbg.generated Tue Jul 09 14:22:52 CST 2019
     */
    public Integer getReplyTotal() {
        return replyTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_circle_comment.reply_total
     *
     * @param replyTotal the value for t_circle_comment.reply_total
     *
     * @mbg.generated Tue Jul 09 14:22:52 CST 2019
     */
    public void setReplyTotal(Integer replyTotal) {
        this.replyTotal = replyTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_circle_comment.create_date
     *
     * @return the value of t_circle_comment.create_date
     *
     * @mbg.generated Tue Jul 09 14:22:52 CST 2019
     */
    @DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone = "GMT+8")
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_circle_comment.create_date
     *
     * @param createDate the value for t_circle_comment.create_date
     *
     * @mbg.generated Tue Jul 09 14:22:52 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}