package com.wyyuand.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CircleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_circle
     *
     * @mbg.generated Tue Jul 09 22:35:00 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_circle
     *
     * @mbg.generated Tue Jul 09 22:35:00 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_circle
     *
     * @mbg.generated Tue Jul 09 22:35:00 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_circle
     *
     * @mbg.generated Tue Jul 09 22:35:00 CST 2019
     */
    public CircleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_circle
     *
     * @mbg.generated Tue Jul 09 22:35:00 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_circle
     *
     * @mbg.generated Tue Jul 09 22:35:00 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_circle
     *
     * @mbg.generated Tue Jul 09 22:35:00 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_circle
     *
     * @mbg.generated Tue Jul 09 22:35:00 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_circle
     *
     * @mbg.generated Tue Jul 09 22:35:00 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_circle
     *
     * @mbg.generated Tue Jul 09 22:35:00 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_circle
     *
     * @mbg.generated Tue Jul 09 22:35:00 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_circle
     *
     * @mbg.generated Tue Jul 09 22:35:00 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_circle
     *
     * @mbg.generated Tue Jul 09 22:35:00 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_circle
     *
     * @mbg.generated Tue Jul 09 22:35:00 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_circle
     *
     * @mbg.generated Tue Jul 09 22:35:00 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCircleIdIsNull() {
            addCriterion("circle_id is null");
            return (Criteria) this;
        }

        public Criteria andCircleIdIsNotNull() {
            addCriterion("circle_id is not null");
            return (Criteria) this;
        }

        public Criteria andCircleIdEqualTo(String value) {
            addCriterion("circle_id =", value, "circleId");
            return (Criteria) this;
        }

        public Criteria andCircleIdNotEqualTo(String value) {
            addCriterion("circle_id <>", value, "circleId");
            return (Criteria) this;
        }

        public Criteria andCircleIdGreaterThan(String value) {
            addCriterion("circle_id >", value, "circleId");
            return (Criteria) this;
        }

        public Criteria andCircleIdGreaterThanOrEqualTo(String value) {
            addCriterion("circle_id >=", value, "circleId");
            return (Criteria) this;
        }

        public Criteria andCircleIdLessThan(String value) {
            addCriterion("circle_id <", value, "circleId");
            return (Criteria) this;
        }

        public Criteria andCircleIdLessThanOrEqualTo(String value) {
            addCriterion("circle_id <=", value, "circleId");
            return (Criteria) this;
        }

        public Criteria andCircleIdLike(String value) {
            addCriterion("circle_id like", value, "circleId");
            return (Criteria) this;
        }

        public Criteria andCircleIdNotLike(String value) {
            addCriterion("circle_id not like", value, "circleId");
            return (Criteria) this;
        }

        public Criteria andCircleIdIn(List<String> values) {
            addCriterion("circle_id in", values, "circleId");
            return (Criteria) this;
        }

        public Criteria andCircleIdNotIn(List<String> values) {
            addCriterion("circle_id not in", values, "circleId");
            return (Criteria) this;
        }

        public Criteria andCircleIdBetween(String value1, String value2) {
            addCriterion("circle_id between", value1, value2, "circleId");
            return (Criteria) this;
        }

        public Criteria andCircleIdNotBetween(String value1, String value2) {
            addCriterion("circle_id not between", value1, value2, "circleId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andCircleThemeIsNull() {
            addCriterion("circle_theme is null");
            return (Criteria) this;
        }

        public Criteria andCircleThemeIsNotNull() {
            addCriterion("circle_theme is not null");
            return (Criteria) this;
        }

        public Criteria andCircleThemeEqualTo(String value) {
            addCriterion("circle_theme =", value, "circleTheme");
            return (Criteria) this;
        }

        public Criteria andCircleThemeNotEqualTo(String value) {
            addCriterion("circle_theme <>", value, "circleTheme");
            return (Criteria) this;
        }

        public Criteria andCircleThemeGreaterThan(String value) {
            addCriterion("circle_theme >", value, "circleTheme");
            return (Criteria) this;
        }

        public Criteria andCircleThemeGreaterThanOrEqualTo(String value) {
            addCriterion("circle_theme >=", value, "circleTheme");
            return (Criteria) this;
        }

        public Criteria andCircleThemeLessThan(String value) {
            addCriterion("circle_theme <", value, "circleTheme");
            return (Criteria) this;
        }

        public Criteria andCircleThemeLessThanOrEqualTo(String value) {
            addCriterion("circle_theme <=", value, "circleTheme");
            return (Criteria) this;
        }

        public Criteria andCircleThemeLike(String value) {
            addCriterion("circle_theme like", value, "circleTheme");
            return (Criteria) this;
        }

        public Criteria andCircleThemeNotLike(String value) {
            addCriterion("circle_theme not like", value, "circleTheme");
            return (Criteria) this;
        }

        public Criteria andCircleThemeIn(List<String> values) {
            addCriterion("circle_theme in", values, "circleTheme");
            return (Criteria) this;
        }

        public Criteria andCircleThemeNotIn(List<String> values) {
            addCriterion("circle_theme not in", values, "circleTheme");
            return (Criteria) this;
        }

        public Criteria andCircleThemeBetween(String value1, String value2) {
            addCriterion("circle_theme between", value1, value2, "circleTheme");
            return (Criteria) this;
        }

        public Criteria andCircleThemeNotBetween(String value1, String value2) {
            addCriterion("circle_theme not between", value1, value2, "circleTheme");
            return (Criteria) this;
        }

        public Criteria andCircleContentIsNull() {
            addCriterion("circle_content is null");
            return (Criteria) this;
        }

        public Criteria andCircleContentIsNotNull() {
            addCriterion("circle_content is not null");
            return (Criteria) this;
        }

        public Criteria andCircleContentEqualTo(String value) {
            addCriterion("circle_content =", value, "circleContent");
            return (Criteria) this;
        }

        public Criteria andCircleContentNotEqualTo(String value) {
            addCriterion("circle_content <>", value, "circleContent");
            return (Criteria) this;
        }

        public Criteria andCircleContentGreaterThan(String value) {
            addCriterion("circle_content >", value, "circleContent");
            return (Criteria) this;
        }

        public Criteria andCircleContentGreaterThanOrEqualTo(String value) {
            addCriterion("circle_content >=", value, "circleContent");
            return (Criteria) this;
        }

        public Criteria andCircleContentLessThan(String value) {
            addCriterion("circle_content <", value, "circleContent");
            return (Criteria) this;
        }

        public Criteria andCircleContentLessThanOrEqualTo(String value) {
            addCriterion("circle_content <=", value, "circleContent");
            return (Criteria) this;
        }

        public Criteria andCircleContentLike(String value) {
            addCriterion("circle_content like", value, "circleContent");
            return (Criteria) this;
        }

        public Criteria andCircleContentNotLike(String value) {
            addCriterion("circle_content not like", value, "circleContent");
            return (Criteria) this;
        }

        public Criteria andCircleContentIn(List<String> values) {
            addCriterion("circle_content in", values, "circleContent");
            return (Criteria) this;
        }

        public Criteria andCircleContentNotIn(List<String> values) {
            addCriterion("circle_content not in", values, "circleContent");
            return (Criteria) this;
        }

        public Criteria andCircleContentBetween(String value1, String value2) {
            addCriterion("circle_content between", value1, value2, "circleContent");
            return (Criteria) this;
        }

        public Criteria andCircleContentNotBetween(String value1, String value2) {
            addCriterion("circle_content not between", value1, value2, "circleContent");
            return (Criteria) this;
        }

        public Criteria andCirclePublicTimeIsNull() {
            addCriterion("circle_public_time is null");
            return (Criteria) this;
        }

        public Criteria andCirclePublicTimeIsNotNull() {
            addCriterion("circle_public_time is not null");
            return (Criteria) this;
        }

        public Criteria andCirclePublicTimeEqualTo(Date value) {
            addCriterion("circle_public_time =", value, "circlePublicTime");
            return (Criteria) this;
        }

        public Criteria andCirclePublicTimeNotEqualTo(Date value) {
            addCriterion("circle_public_time <>", value, "circlePublicTime");
            return (Criteria) this;
        }

        public Criteria andCirclePublicTimeGreaterThan(Date value) {
            addCriterion("circle_public_time >", value, "circlePublicTime");
            return (Criteria) this;
        }

        public Criteria andCirclePublicTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("circle_public_time >=", value, "circlePublicTime");
            return (Criteria) this;
        }

        public Criteria andCirclePublicTimeLessThan(Date value) {
            addCriterion("circle_public_time <", value, "circlePublicTime");
            return (Criteria) this;
        }

        public Criteria andCirclePublicTimeLessThanOrEqualTo(Date value) {
            addCriterion("circle_public_time <=", value, "circlePublicTime");
            return (Criteria) this;
        }

        public Criteria andCirclePublicTimeIn(List<Date> values) {
            addCriterion("circle_public_time in", values, "circlePublicTime");
            return (Criteria) this;
        }

        public Criteria andCirclePublicTimeNotIn(List<Date> values) {
            addCriterion("circle_public_time not in", values, "circlePublicTime");
            return (Criteria) this;
        }

        public Criteria andCirclePublicTimeBetween(Date value1, Date value2) {
            addCriterion("circle_public_time between", value1, value2, "circlePublicTime");
            return (Criteria) this;
        }

        public Criteria andCirclePublicTimeNotBetween(Date value1, Date value2) {
            addCriterion("circle_public_time not between", value1, value2, "circlePublicTime");
            return (Criteria) this;
        }

        public Criteria andFllowNumIsNull() {
            addCriterion("fllow_num is null");
            return (Criteria) this;
        }

        public Criteria andFllowNumIsNotNull() {
            addCriterion("fllow_num is not null");
            return (Criteria) this;
        }

        public Criteria andFllowNumEqualTo(Integer value) {
            addCriterion("fllow_num =", value, "fllowNum");
            return (Criteria) this;
        }

        public Criteria andFllowNumNotEqualTo(Integer value) {
            addCriterion("fllow_num <>", value, "fllowNum");
            return (Criteria) this;
        }

        public Criteria andFllowNumGreaterThan(Integer value) {
            addCriterion("fllow_num >", value, "fllowNum");
            return (Criteria) this;
        }

        public Criteria andFllowNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("fllow_num >=", value, "fllowNum");
            return (Criteria) this;
        }

        public Criteria andFllowNumLessThan(Integer value) {
            addCriterion("fllow_num <", value, "fllowNum");
            return (Criteria) this;
        }

        public Criteria andFllowNumLessThanOrEqualTo(Integer value) {
            addCriterion("fllow_num <=", value, "fllowNum");
            return (Criteria) this;
        }

        public Criteria andFllowNumIn(List<Integer> values) {
            addCriterion("fllow_num in", values, "fllowNum");
            return (Criteria) this;
        }

        public Criteria andFllowNumNotIn(List<Integer> values) {
            addCriterion("fllow_num not in", values, "fllowNum");
            return (Criteria) this;
        }

        public Criteria andFllowNumBetween(Integer value1, Integer value2) {
            addCriterion("fllow_num between", value1, value2, "fllowNum");
            return (Criteria) this;
        }

        public Criteria andFllowNumNotBetween(Integer value1, Integer value2) {
            addCriterion("fllow_num not between", value1, value2, "fllowNum");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_circle
     *
     * @mbg.generated do_not_delete_during_merge Tue Jul 09 22:35:00 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_circle
     *
     * @mbg.generated Tue Jul 09 22:35:00 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}