package com.wyyuand.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FoodExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_food
     *
     * @mbg.generated Thu Jun 27 08:06:28 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_food
     *
     * @mbg.generated Thu Jun 27 08:06:28 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_food
     *
     * @mbg.generated Thu Jun 27 08:06:28 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_food
     *
     * @mbg.generated Thu Jun 27 08:06:28 CST 2019
     */
    public FoodExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_food
     *
     * @mbg.generated Thu Jun 27 08:06:28 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_food
     *
     * @mbg.generated Thu Jun 27 08:06:28 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_food
     *
     * @mbg.generated Thu Jun 27 08:06:28 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_food
     *
     * @mbg.generated Thu Jun 27 08:06:28 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_food
     *
     * @mbg.generated Thu Jun 27 08:06:28 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_food
     *
     * @mbg.generated Thu Jun 27 08:06:28 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_food
     *
     * @mbg.generated Thu Jun 27 08:06:28 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_food
     *
     * @mbg.generated Thu Jun 27 08:06:28 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_food
     *
     * @mbg.generated Thu Jun 27 08:06:28 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_food
     *
     * @mbg.generated Thu Jun 27 08:06:28 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_food
     *
     * @mbg.generated Thu Jun 27 08:06:28 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andVarietyIsNull() {
            addCriterion("variety is null");
            return (Criteria) this;
        }

        public Criteria andVarietyIsNotNull() {
            addCriterion("variety is not null");
            return (Criteria) this;
        }

        public Criteria andVarietyEqualTo(String value) {
            addCriterion("variety =", value, "variety");
            return (Criteria) this;
        }

        public Criteria andVarietyNotEqualTo(String value) {
            addCriterion("variety <>", value, "variety");
            return (Criteria) this;
        }

        public Criteria andVarietyGreaterThan(String value) {
            addCriterion("variety >", value, "variety");
            return (Criteria) this;
        }

        public Criteria andVarietyGreaterThanOrEqualTo(String value) {
            addCriterion("variety >=", value, "variety");
            return (Criteria) this;
        }

        public Criteria andVarietyLessThan(String value) {
            addCriterion("variety <", value, "variety");
            return (Criteria) this;
        }

        public Criteria andVarietyLessThanOrEqualTo(String value) {
            addCriterion("variety <=", value, "variety");
            return (Criteria) this;
        }

        public Criteria andVarietyLike(String value) {
            addCriterion("variety like", value, "variety");
            return (Criteria) this;
        }

        public Criteria andVarietyNotLike(String value) {
            addCriterion("variety not like", value, "variety");
            return (Criteria) this;
        }

        public Criteria andVarietyIn(List<String> values) {
            addCriterion("variety in", values, "variety");
            return (Criteria) this;
        }

        public Criteria andVarietyNotIn(List<String> values) {
            addCriterion("variety not in", values, "variety");
            return (Criteria) this;
        }

        public Criteria andVarietyBetween(String value1, String value2) {
            addCriterion("variety between", value1, value2, "variety");
            return (Criteria) this;
        }

        public Criteria andVarietyNotBetween(String value1, String value2) {
            addCriterion("variety not between", value1, value2, "variety");
            return (Criteria) this;
        }

        public Criteria andAliasIsNull() {
            addCriterion("alias is null");
            return (Criteria) this;
        }

        public Criteria andAliasIsNotNull() {
            addCriterion("alias is not null");
            return (Criteria) this;
        }

        public Criteria andAliasEqualTo(String value) {
            addCriterion("alias =", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasNotEqualTo(String value) {
            addCriterion("alias <>", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasGreaterThan(String value) {
            addCriterion("alias >", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasGreaterThanOrEqualTo(String value) {
            addCriterion("alias >=", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasLessThan(String value) {
            addCriterion("alias <", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasLessThanOrEqualTo(String value) {
            addCriterion("alias <=", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasLike(String value) {
            addCriterion("alias like", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasNotLike(String value) {
            addCriterion("alias not like", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasIn(List<String> values) {
            addCriterion("alias in", values, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasNotIn(List<String> values) {
            addCriterion("alias not in", values, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasBetween(String value1, String value2) {
            addCriterion("alias between", value1, value2, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasNotBetween(String value1, String value2) {
            addCriterion("alias not between", value1, value2, "alias");
            return (Criteria) this;
        }

        public Criteria andPwJIsNull() {
            addCriterion("pw_j is null");
            return (Criteria) this;
        }

        public Criteria andPwJIsNotNull() {
            addCriterion("pw_j is not null");
            return (Criteria) this;
        }

        public Criteria andPwJEqualTo(String value) {
            addCriterion("pw_j =", value, "pwJ");
            return (Criteria) this;
        }

        public Criteria andPwJNotEqualTo(String value) {
            addCriterion("pw_j <>", value, "pwJ");
            return (Criteria) this;
        }

        public Criteria andPwJGreaterThan(String value) {
            addCriterion("pw_j >", value, "pwJ");
            return (Criteria) this;
        }

        public Criteria andPwJGreaterThanOrEqualTo(String value) {
            addCriterion("pw_j >=", value, "pwJ");
            return (Criteria) this;
        }

        public Criteria andPwJLessThan(String value) {
            addCriterion("pw_j <", value, "pwJ");
            return (Criteria) this;
        }

        public Criteria andPwJLessThanOrEqualTo(String value) {
            addCriterion("pw_j <=", value, "pwJ");
            return (Criteria) this;
        }

        public Criteria andPwJLike(String value) {
            addCriterion("pw_j like", value, "pwJ");
            return (Criteria) this;
        }

        public Criteria andPwJNotLike(String value) {
            addCriterion("pw_j not like", value, "pwJ");
            return (Criteria) this;
        }

        public Criteria andPwJIn(List<String> values) {
            addCriterion("pw_j in", values, "pwJ");
            return (Criteria) this;
        }

        public Criteria andPwJNotIn(List<String> values) {
            addCriterion("pw_j not in", values, "pwJ");
            return (Criteria) this;
        }

        public Criteria andPwJBetween(String value1, String value2) {
            addCriterion("pw_j between", value1, value2, "pwJ");
            return (Criteria) this;
        }

        public Criteria andPwJNotBetween(String value1, String value2) {
            addCriterion("pw_j not between", value1, value2, "pwJ");
            return (Criteria) this;
        }

        public Criteria andPwIsNull() {
            addCriterion("pw is null");
            return (Criteria) this;
        }

        public Criteria andPwIsNotNull() {
            addCriterion("pw is not null");
            return (Criteria) this;
        }

        public Criteria andPwEqualTo(String value) {
            addCriterion("pw =", value, "pw");
            return (Criteria) this;
        }

        public Criteria andPwNotEqualTo(String value) {
            addCriterion("pw <>", value, "pw");
            return (Criteria) this;
        }

        public Criteria andPwGreaterThan(String value) {
            addCriterion("pw >", value, "pw");
            return (Criteria) this;
        }

        public Criteria andPwGreaterThanOrEqualTo(String value) {
            addCriterion("pw >=", value, "pw");
            return (Criteria) this;
        }

        public Criteria andPwLessThan(String value) {
            addCriterion("pw <", value, "pw");
            return (Criteria) this;
        }

        public Criteria andPwLessThanOrEqualTo(String value) {
            addCriterion("pw <=", value, "pw");
            return (Criteria) this;
        }

        public Criteria andPwLike(String value) {
            addCriterion("pw like", value, "pw");
            return (Criteria) this;
        }

        public Criteria andPwNotLike(String value) {
            addCriterion("pw not like", value, "pw");
            return (Criteria) this;
        }

        public Criteria andPwIn(List<String> values) {
            addCriterion("pw in", values, "pw");
            return (Criteria) this;
        }

        public Criteria andPwNotIn(List<String> values) {
            addCriterion("pw not in", values, "pw");
            return (Criteria) this;
        }

        public Criteria andPwBetween(String value1, String value2) {
            addCriterion("pw between", value1, value2, "pw");
            return (Criteria) this;
        }

        public Criteria andPwNotBetween(String value1, String value2) {
            addCriterion("pw not between", value1, value2, "pw");
            return (Criteria) this;
        }

        public Criteria andParturientJIsNull() {
            addCriterion("parturient_j is null");
            return (Criteria) this;
        }

        public Criteria andParturientJIsNotNull() {
            addCriterion("parturient_j is not null");
            return (Criteria) this;
        }

        public Criteria andParturientJEqualTo(String value) {
            addCriterion("parturient_j =", value, "parturientJ");
            return (Criteria) this;
        }

        public Criteria andParturientJNotEqualTo(String value) {
            addCriterion("parturient_j <>", value, "parturientJ");
            return (Criteria) this;
        }

        public Criteria andParturientJGreaterThan(String value) {
            addCriterion("parturient_j >", value, "parturientJ");
            return (Criteria) this;
        }

        public Criteria andParturientJGreaterThanOrEqualTo(String value) {
            addCriterion("parturient_j >=", value, "parturientJ");
            return (Criteria) this;
        }

        public Criteria andParturientJLessThan(String value) {
            addCriterion("parturient_j <", value, "parturientJ");
            return (Criteria) this;
        }

        public Criteria andParturientJLessThanOrEqualTo(String value) {
            addCriterion("parturient_j <=", value, "parturientJ");
            return (Criteria) this;
        }

        public Criteria andParturientJLike(String value) {
            addCriterion("parturient_j like", value, "parturientJ");
            return (Criteria) this;
        }

        public Criteria andParturientJNotLike(String value) {
            addCriterion("parturient_j not like", value, "parturientJ");
            return (Criteria) this;
        }

        public Criteria andParturientJIn(List<String> values) {
            addCriterion("parturient_j in", values, "parturientJ");
            return (Criteria) this;
        }

        public Criteria andParturientJNotIn(List<String> values) {
            addCriterion("parturient_j not in", values, "parturientJ");
            return (Criteria) this;
        }

        public Criteria andParturientJBetween(String value1, String value2) {
            addCriterion("parturient_j between", value1, value2, "parturientJ");
            return (Criteria) this;
        }

        public Criteria andParturientJNotBetween(String value1, String value2) {
            addCriterion("parturient_j not between", value1, value2, "parturientJ");
            return (Criteria) this;
        }

        public Criteria andParturientIsNull() {
            addCriterion("parturient is null");
            return (Criteria) this;
        }

        public Criteria andParturientIsNotNull() {
            addCriterion("parturient is not null");
            return (Criteria) this;
        }

        public Criteria andParturientEqualTo(String value) {
            addCriterion("parturient =", value, "parturient");
            return (Criteria) this;
        }

        public Criteria andParturientNotEqualTo(String value) {
            addCriterion("parturient <>", value, "parturient");
            return (Criteria) this;
        }

        public Criteria andParturientGreaterThan(String value) {
            addCriterion("parturient >", value, "parturient");
            return (Criteria) this;
        }

        public Criteria andParturientGreaterThanOrEqualTo(String value) {
            addCriterion("parturient >=", value, "parturient");
            return (Criteria) this;
        }

        public Criteria andParturientLessThan(String value) {
            addCriterion("parturient <", value, "parturient");
            return (Criteria) this;
        }

        public Criteria andParturientLessThanOrEqualTo(String value) {
            addCriterion("parturient <=", value, "parturient");
            return (Criteria) this;
        }

        public Criteria andParturientLike(String value) {
            addCriterion("parturient like", value, "parturient");
            return (Criteria) this;
        }

        public Criteria andParturientNotLike(String value) {
            addCriterion("parturient not like", value, "parturient");
            return (Criteria) this;
        }

        public Criteria andParturientIn(List<String> values) {
            addCriterion("parturient in", values, "parturient");
            return (Criteria) this;
        }

        public Criteria andParturientNotIn(List<String> values) {
            addCriterion("parturient not in", values, "parturient");
            return (Criteria) this;
        }

        public Criteria andParturientBetween(String value1, String value2) {
            addCriterion("parturient between", value1, value2, "parturient");
            return (Criteria) this;
        }

        public Criteria andParturientNotBetween(String value1, String value2) {
            addCriterion("parturient not between", value1, value2, "parturient");
            return (Criteria) this;
        }

        public Criteria andBfpJIsNull() {
            addCriterion("bfp_j is null");
            return (Criteria) this;
        }

        public Criteria andBfpJIsNotNull() {
            addCriterion("bfp_j is not null");
            return (Criteria) this;
        }

        public Criteria andBfpJEqualTo(String value) {
            addCriterion("bfp_j =", value, "bfpJ");
            return (Criteria) this;
        }

        public Criteria andBfpJNotEqualTo(String value) {
            addCriterion("bfp_j <>", value, "bfpJ");
            return (Criteria) this;
        }

        public Criteria andBfpJGreaterThan(String value) {
            addCriterion("bfp_j >", value, "bfpJ");
            return (Criteria) this;
        }

        public Criteria andBfpJGreaterThanOrEqualTo(String value) {
            addCriterion("bfp_j >=", value, "bfpJ");
            return (Criteria) this;
        }

        public Criteria andBfpJLessThan(String value) {
            addCriterion("bfp_j <", value, "bfpJ");
            return (Criteria) this;
        }

        public Criteria andBfpJLessThanOrEqualTo(String value) {
            addCriterion("bfp_j <=", value, "bfpJ");
            return (Criteria) this;
        }

        public Criteria andBfpJLike(String value) {
            addCriterion("bfp_j like", value, "bfpJ");
            return (Criteria) this;
        }

        public Criteria andBfpJNotLike(String value) {
            addCriterion("bfp_j not like", value, "bfpJ");
            return (Criteria) this;
        }

        public Criteria andBfpJIn(List<String> values) {
            addCriterion("bfp_j in", values, "bfpJ");
            return (Criteria) this;
        }

        public Criteria andBfpJNotIn(List<String> values) {
            addCriterion("bfp_j not in", values, "bfpJ");
            return (Criteria) this;
        }

        public Criteria andBfpJBetween(String value1, String value2) {
            addCriterion("bfp_j between", value1, value2, "bfpJ");
            return (Criteria) this;
        }

        public Criteria andBfpJNotBetween(String value1, String value2) {
            addCriterion("bfp_j not between", value1, value2, "bfpJ");
            return (Criteria) this;
        }

        public Criteria andBfpIsNull() {
            addCriterion("bfp is null");
            return (Criteria) this;
        }

        public Criteria andBfpIsNotNull() {
            addCriterion("bfp is not null");
            return (Criteria) this;
        }

        public Criteria andBfpEqualTo(String value) {
            addCriterion("bfp =", value, "bfp");
            return (Criteria) this;
        }

        public Criteria andBfpNotEqualTo(String value) {
            addCriterion("bfp <>", value, "bfp");
            return (Criteria) this;
        }

        public Criteria andBfpGreaterThan(String value) {
            addCriterion("bfp >", value, "bfp");
            return (Criteria) this;
        }

        public Criteria andBfpGreaterThanOrEqualTo(String value) {
            addCriterion("bfp >=", value, "bfp");
            return (Criteria) this;
        }

        public Criteria andBfpLessThan(String value) {
            addCriterion("bfp <", value, "bfp");
            return (Criteria) this;
        }

        public Criteria andBfpLessThanOrEqualTo(String value) {
            addCriterion("bfp <=", value, "bfp");
            return (Criteria) this;
        }

        public Criteria andBfpLike(String value) {
            addCriterion("bfp like", value, "bfp");
            return (Criteria) this;
        }

        public Criteria andBfpNotLike(String value) {
            addCriterion("bfp not like", value, "bfp");
            return (Criteria) this;
        }

        public Criteria andBfpIn(List<String> values) {
            addCriterion("bfp in", values, "bfp");
            return (Criteria) this;
        }

        public Criteria andBfpNotIn(List<String> values) {
            addCriterion("bfp not in", values, "bfp");
            return (Criteria) this;
        }

        public Criteria andBfpBetween(String value1, String value2) {
            addCriterion("bfp between", value1, value2, "bfp");
            return (Criteria) this;
        }

        public Criteria andBfpNotBetween(String value1, String value2) {
            addCriterion("bfp not between", value1, value2, "bfp");
            return (Criteria) this;
        }

        public Criteria andBabyJIsNull() {
            addCriterion("baby_j is null");
            return (Criteria) this;
        }

        public Criteria andBabyJIsNotNull() {
            addCriterion("baby_j is not null");
            return (Criteria) this;
        }

        public Criteria andBabyJEqualTo(String value) {
            addCriterion("baby_j =", value, "babyJ");
            return (Criteria) this;
        }

        public Criteria andBabyJNotEqualTo(String value) {
            addCriterion("baby_j <>", value, "babyJ");
            return (Criteria) this;
        }

        public Criteria andBabyJGreaterThan(String value) {
            addCriterion("baby_j >", value, "babyJ");
            return (Criteria) this;
        }

        public Criteria andBabyJGreaterThanOrEqualTo(String value) {
            addCriterion("baby_j >=", value, "babyJ");
            return (Criteria) this;
        }

        public Criteria andBabyJLessThan(String value) {
            addCriterion("baby_j <", value, "babyJ");
            return (Criteria) this;
        }

        public Criteria andBabyJLessThanOrEqualTo(String value) {
            addCriterion("baby_j <=", value, "babyJ");
            return (Criteria) this;
        }

        public Criteria andBabyJLike(String value) {
            addCriterion("baby_j like", value, "babyJ");
            return (Criteria) this;
        }

        public Criteria andBabyJNotLike(String value) {
            addCriterion("baby_j not like", value, "babyJ");
            return (Criteria) this;
        }

        public Criteria andBabyJIn(List<String> values) {
            addCriterion("baby_j in", values, "babyJ");
            return (Criteria) this;
        }

        public Criteria andBabyJNotIn(List<String> values) {
            addCriterion("baby_j not in", values, "babyJ");
            return (Criteria) this;
        }

        public Criteria andBabyJBetween(String value1, String value2) {
            addCriterion("baby_j between", value1, value2, "babyJ");
            return (Criteria) this;
        }

        public Criteria andBabyJNotBetween(String value1, String value2) {
            addCriterion("baby_j not between", value1, value2, "babyJ");
            return (Criteria) this;
        }

        public Criteria andBabyIsNull() {
            addCriterion("baby is null");
            return (Criteria) this;
        }

        public Criteria andBabyIsNotNull() {
            addCriterion("baby is not null");
            return (Criteria) this;
        }

        public Criteria andBabyEqualTo(String value) {
            addCriterion("baby =", value, "baby");
            return (Criteria) this;
        }

        public Criteria andBabyNotEqualTo(String value) {
            addCriterion("baby <>", value, "baby");
            return (Criteria) this;
        }

        public Criteria andBabyGreaterThan(String value) {
            addCriterion("baby >", value, "baby");
            return (Criteria) this;
        }

        public Criteria andBabyGreaterThanOrEqualTo(String value) {
            addCriterion("baby >=", value, "baby");
            return (Criteria) this;
        }

        public Criteria andBabyLessThan(String value) {
            addCriterion("baby <", value, "baby");
            return (Criteria) this;
        }

        public Criteria andBabyLessThanOrEqualTo(String value) {
            addCriterion("baby <=", value, "baby");
            return (Criteria) this;
        }

        public Criteria andBabyLike(String value) {
            addCriterion("baby like", value, "baby");
            return (Criteria) this;
        }

        public Criteria andBabyNotLike(String value) {
            addCriterion("baby not like", value, "baby");
            return (Criteria) this;
        }

        public Criteria andBabyIn(List<String> values) {
            addCriterion("baby in", values, "baby");
            return (Criteria) this;
        }

        public Criteria andBabyNotIn(List<String> values) {
            addCriterion("baby not in", values, "baby");
            return (Criteria) this;
        }

        public Criteria andBabyBetween(String value1, String value2) {
            addCriterion("baby between", value1, value2, "baby");
            return (Criteria) this;
        }

        public Criteria andBabyNotBetween(String value1, String value2) {
            addCriterion("baby not between", value1, value2, "baby");
            return (Criteria) this;
        }

        public Criteria andEfficacyIsNull() {
            addCriterion("efficacy is null");
            return (Criteria) this;
        }

        public Criteria andEfficacyIsNotNull() {
            addCriterion("efficacy is not null");
            return (Criteria) this;
        }

        public Criteria andEfficacyEqualTo(String value) {
            addCriterion("efficacy =", value, "efficacy");
            return (Criteria) this;
        }

        public Criteria andEfficacyNotEqualTo(String value) {
            addCriterion("efficacy <>", value, "efficacy");
            return (Criteria) this;
        }

        public Criteria andEfficacyGreaterThan(String value) {
            addCriterion("efficacy >", value, "efficacy");
            return (Criteria) this;
        }

        public Criteria andEfficacyGreaterThanOrEqualTo(String value) {
            addCriterion("efficacy >=", value, "efficacy");
            return (Criteria) this;
        }

        public Criteria andEfficacyLessThan(String value) {
            addCriterion("efficacy <", value, "efficacy");
            return (Criteria) this;
        }

        public Criteria andEfficacyLessThanOrEqualTo(String value) {
            addCriterion("efficacy <=", value, "efficacy");
            return (Criteria) this;
        }

        public Criteria andEfficacyLike(String value) {
            addCriterion("efficacy like", value, "efficacy");
            return (Criteria) this;
        }

        public Criteria andEfficacyNotLike(String value) {
            addCriterion("efficacy not like", value, "efficacy");
            return (Criteria) this;
        }

        public Criteria andEfficacyIn(List<String> values) {
            addCriterion("efficacy in", values, "efficacy");
            return (Criteria) this;
        }

        public Criteria andEfficacyNotIn(List<String> values) {
            addCriterion("efficacy not in", values, "efficacy");
            return (Criteria) this;
        }

        public Criteria andEfficacyBetween(String value1, String value2) {
            addCriterion("efficacy between", value1, value2, "efficacy");
            return (Criteria) this;
        }

        public Criteria andEfficacyNotBetween(String value1, String value2) {
            addCriterion("efficacy not between", value1, value2, "efficacy");
            return (Criteria) this;
        }

        public Criteria andBuyIsNull() {
            addCriterion("buy is null");
            return (Criteria) this;
        }

        public Criteria andBuyIsNotNull() {
            addCriterion("buy is not null");
            return (Criteria) this;
        }

        public Criteria andBuyEqualTo(String value) {
            addCriterion("buy =", value, "buy");
            return (Criteria) this;
        }

        public Criteria andBuyNotEqualTo(String value) {
            addCriterion("buy <>", value, "buy");
            return (Criteria) this;
        }

        public Criteria andBuyGreaterThan(String value) {
            addCriterion("buy >", value, "buy");
            return (Criteria) this;
        }

        public Criteria andBuyGreaterThanOrEqualTo(String value) {
            addCriterion("buy >=", value, "buy");
            return (Criteria) this;
        }

        public Criteria andBuyLessThan(String value) {
            addCriterion("buy <", value, "buy");
            return (Criteria) this;
        }

        public Criteria andBuyLessThanOrEqualTo(String value) {
            addCriterion("buy <=", value, "buy");
            return (Criteria) this;
        }

        public Criteria andBuyLike(String value) {
            addCriterion("buy like", value, "buy");
            return (Criteria) this;
        }

        public Criteria andBuyNotLike(String value) {
            addCriterion("buy not like", value, "buy");
            return (Criteria) this;
        }

        public Criteria andBuyIn(List<String> values) {
            addCriterion("buy in", values, "buy");
            return (Criteria) this;
        }

        public Criteria andBuyNotIn(List<String> values) {
            addCriterion("buy not in", values, "buy");
            return (Criteria) this;
        }

        public Criteria andBuyBetween(String value1, String value2) {
            addCriterion("buy between", value1, value2, "buy");
            return (Criteria) this;
        }

        public Criteria andBuyNotBetween(String value1, String value2) {
            addCriterion("buy not between", value1, value2, "buy");
            return (Criteria) this;
        }

        public Criteria andEatingIsNull() {
            addCriterion("eating is null");
            return (Criteria) this;
        }

        public Criteria andEatingIsNotNull() {
            addCriterion("eating is not null");
            return (Criteria) this;
        }

        public Criteria andEatingEqualTo(String value) {
            addCriterion("eating =", value, "eating");
            return (Criteria) this;
        }

        public Criteria andEatingNotEqualTo(String value) {
            addCriterion("eating <>", value, "eating");
            return (Criteria) this;
        }

        public Criteria andEatingGreaterThan(String value) {
            addCriterion("eating >", value, "eating");
            return (Criteria) this;
        }

        public Criteria andEatingGreaterThanOrEqualTo(String value) {
            addCriterion("eating >=", value, "eating");
            return (Criteria) this;
        }

        public Criteria andEatingLessThan(String value) {
            addCriterion("eating <", value, "eating");
            return (Criteria) this;
        }

        public Criteria andEatingLessThanOrEqualTo(String value) {
            addCriterion("eating <=", value, "eating");
            return (Criteria) this;
        }

        public Criteria andEatingLike(String value) {
            addCriterion("eating like", value, "eating");
            return (Criteria) this;
        }

        public Criteria andEatingNotLike(String value) {
            addCriterion("eating not like", value, "eating");
            return (Criteria) this;
        }

        public Criteria andEatingIn(List<String> values) {
            addCriterion("eating in", values, "eating");
            return (Criteria) this;
        }

        public Criteria andEatingNotIn(List<String> values) {
            addCriterion("eating not in", values, "eating");
            return (Criteria) this;
        }

        public Criteria andEatingBetween(String value1, String value2) {
            addCriterion("eating between", value1, value2, "eating");
            return (Criteria) this;
        }

        public Criteria andEatingNotBetween(String value1, String value2) {
            addCriterion("eating not between", value1, value2, "eating");
            return (Criteria) this;
        }

        public Criteria andPictureIsNull() {
            addCriterion("picture is null");
            return (Criteria) this;
        }

        public Criteria andPictureIsNotNull() {
            addCriterion("picture is not null");
            return (Criteria) this;
        }

        public Criteria andPictureEqualTo(String value) {
            addCriterion("picture =", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureNotEqualTo(String value) {
            addCriterion("picture <>", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureGreaterThan(String value) {
            addCriterion("picture >", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureGreaterThanOrEqualTo(String value) {
            addCriterion("picture >=", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureLessThan(String value) {
            addCriterion("picture <", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureLessThanOrEqualTo(String value) {
            addCriterion("picture <=", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureLike(String value) {
            addCriterion("picture like", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureNotLike(String value) {
            addCriterion("picture not like", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureIn(List<String> values) {
            addCriterion("picture in", values, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureNotIn(List<String> values) {
            addCriterion("picture not in", values, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureBetween(String value1, String value2) {
            addCriterion("picture between", value1, value2, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureNotBetween(String value1, String value2) {
            addCriterion("picture not between", value1, value2, "picture");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNull() {
            addCriterion("updatetime is null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNotNull() {
            addCriterion("updatetime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeEqualTo(Date value) {
            addCriterion("updatetime =", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotEqualTo(Date value) {
            addCriterion("updatetime <>", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThan(Date value) {
            addCriterion("updatetime >", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("updatetime >=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThan(Date value) {
            addCriterion("updatetime <", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThanOrEqualTo(Date value) {
            addCriterion("updatetime <=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIn(List<Date> values) {
            addCriterion("updatetime in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotIn(List<Date> values) {
            addCriterion("updatetime not in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeBetween(Date value1, Date value2) {
            addCriterion("updatetime between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotBetween(Date value1, Date value2) {
            addCriterion("updatetime not between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andPwUsuallyEatIsNull() {
            addCriterion("pw_usually_eat is null");
            return (Criteria) this;
        }

        public Criteria andPwUsuallyEatIsNotNull() {
            addCriterion("pw_usually_eat is not null");
            return (Criteria) this;
        }

        public Criteria andPwUsuallyEatEqualTo(String value) {
            addCriterion("pw_usually_eat =", value, "pwUsuallyEat");
            return (Criteria) this;
        }

        public Criteria andPwUsuallyEatNotEqualTo(String value) {
            addCriterion("pw_usually_eat <>", value, "pwUsuallyEat");
            return (Criteria) this;
        }

        public Criteria andPwUsuallyEatGreaterThan(String value) {
            addCriterion("pw_usually_eat >", value, "pwUsuallyEat");
            return (Criteria) this;
        }

        public Criteria andPwUsuallyEatGreaterThanOrEqualTo(String value) {
            addCriterion("pw_usually_eat >=", value, "pwUsuallyEat");
            return (Criteria) this;
        }

        public Criteria andPwUsuallyEatLessThan(String value) {
            addCriterion("pw_usually_eat <", value, "pwUsuallyEat");
            return (Criteria) this;
        }

        public Criteria andPwUsuallyEatLessThanOrEqualTo(String value) {
            addCriterion("pw_usually_eat <=", value, "pwUsuallyEat");
            return (Criteria) this;
        }

        public Criteria andPwUsuallyEatLike(String value) {
            addCriterion("pw_usually_eat like", value, "pwUsuallyEat");
            return (Criteria) this;
        }

        public Criteria andPwUsuallyEatNotLike(String value) {
            addCriterion("pw_usually_eat not like", value, "pwUsuallyEat");
            return (Criteria) this;
        }

        public Criteria andPwUsuallyEatIn(List<String> values) {
            addCriterion("pw_usually_eat in", values, "pwUsuallyEat");
            return (Criteria) this;
        }

        public Criteria andPwUsuallyEatNotIn(List<String> values) {
            addCriterion("pw_usually_eat not in", values, "pwUsuallyEat");
            return (Criteria) this;
        }

        public Criteria andPwUsuallyEatBetween(String value1, String value2) {
            addCriterion("pw_usually_eat between", value1, value2, "pwUsuallyEat");
            return (Criteria) this;
        }

        public Criteria andPwUsuallyEatNotBetween(String value1, String value2) {
            addCriterion("pw_usually_eat not between", value1, value2, "pwUsuallyEat");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_food
     *
     * @mbg.generated do_not_delete_during_merge Thu Jun 27 08:06:28 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_food
     *
     * @mbg.generated Thu Jun 27 08:06:28 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}