package com.wyyuand.domain;

import java.util.Date;

public class Knowledge {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_knowledge.id
     *
     * @mbg.generated Sat Jun 29 15:45:35 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_knowledge.title
     *
     * @mbg.generated Sat Jun 29 15:45:35 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_knowledge.content
     *
     * @mbg.generated Sat Jun 29 15:45:35 CST 2019
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_knowledge.publishDate
     *
     * @mbg.generated Sat Jun 29 15:45:35 CST 2019
     */
    private Date publishdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_knowledge.author
     *
     * @mbg.generated Sat Jun 29 15:45:35 CST 2019
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_knowledge.status
     *
     * @mbg.generated Sat Jun 29 15:45:35 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_knowledge.images
     *
     * @mbg.generated Sat Jun 29 15:45:35 CST 2019
     */
    private String images;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_knowledge.id
     *
     * @return the value of t_knowledge.id
     *
     * @mbg.generated Sat Jun 29 15:45:35 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_knowledge.id
     *
     * @param id the value for t_knowledge.id
     *
     * @mbg.generated Sat Jun 29 15:45:35 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_knowledge.title
     *
     * @return the value of t_knowledge.title
     *
     * @mbg.generated Sat Jun 29 15:45:35 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_knowledge.title
     *
     * @param title the value for t_knowledge.title
     *
     * @mbg.generated Sat Jun 29 15:45:35 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_knowledge.content
     *
     * @return the value of t_knowledge.content
     *
     * @mbg.generated Sat Jun 29 15:45:35 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_knowledge.content
     *
     * @param content the value for t_knowledge.content
     *
     * @mbg.generated Sat Jun 29 15:45:35 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_knowledge.publishDate
     *
     * @return the value of t_knowledge.publishDate
     *
     * @mbg.generated Sat Jun 29 15:45:35 CST 2019
     */
    public Date getPublishdate() {
        return publishdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_knowledge.publishDate
     *
     * @param publishdate the value for t_knowledge.publishDate
     *
     * @mbg.generated Sat Jun 29 15:45:35 CST 2019
     */
    public void setPublishdate(Date publishdate) {
        this.publishdate = publishdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_knowledge.author
     *
     * @return the value of t_knowledge.author
     *
     * @mbg.generated Sat Jun 29 15:45:35 CST 2019
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_knowledge.author
     *
     * @param author the value for t_knowledge.author
     *
     * @mbg.generated Sat Jun 29 15:45:35 CST 2019
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_knowledge.status
     *
     * @return the value of t_knowledge.status
     *
     * @mbg.generated Sat Jun 29 15:45:35 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_knowledge.status
     *
     * @param status the value for t_knowledge.status
     *
     * @mbg.generated Sat Jun 29 15:45:35 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_knowledge.images
     *
     * @return the value of t_knowledge.images
     *
     * @mbg.generated Sat Jun 29 15:45:35 CST 2019
     */
    public String getImages() {
        return images;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_knowledge.images
     *
     * @param images the value for t_knowledge.images
     *
     * @mbg.generated Sat Jun 29 15:45:35 CST 2019
     */
    public void setImages(String images) {
        this.images = images == null ? null : images.trim();
    }
}