package com.wyyuand.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MusicExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_music
     *
     * @mbg.generated Mon Jul 01 10:36:07 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_music
     *
     * @mbg.generated Mon Jul 01 10:36:07 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_music
     *
     * @mbg.generated Mon Jul 01 10:36:07 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_music
     *
     * @mbg.generated Mon Jul 01 10:36:07 CST 2019
     */
    public MusicExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_music
     *
     * @mbg.generated Mon Jul 01 10:36:07 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_music
     *
     * @mbg.generated Mon Jul 01 10:36:07 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_music
     *
     * @mbg.generated Mon Jul 01 10:36:07 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_music
     *
     * @mbg.generated Mon Jul 01 10:36:07 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_music
     *
     * @mbg.generated Mon Jul 01 10:36:07 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_music
     *
     * @mbg.generated Mon Jul 01 10:36:07 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_music
     *
     * @mbg.generated Mon Jul 01 10:36:07 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_music
     *
     * @mbg.generated Mon Jul 01 10:36:07 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_music
     *
     * @mbg.generated Mon Jul 01 10:36:07 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_music
     *
     * @mbg.generated Mon Jul 01 10:36:07 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_music
     *
     * @mbg.generated Mon Jul 01 10:36:07 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMusicIdIsNull() {
            addCriterion("music_id is null");
            return (Criteria) this;
        }

        public Criteria andMusicIdIsNotNull() {
            addCriterion("music_id is not null");
            return (Criteria) this;
        }

        public Criteria andMusicIdEqualTo(String value) {
            addCriterion("music_id =", value, "musicId");
            return (Criteria) this;
        }

        public Criteria andMusicIdNotEqualTo(String value) {
            addCriterion("music_id <>", value, "musicId");
            return (Criteria) this;
        }

        public Criteria andMusicIdGreaterThan(String value) {
            addCriterion("music_id >", value, "musicId");
            return (Criteria) this;
        }

        public Criteria andMusicIdGreaterThanOrEqualTo(String value) {
            addCriterion("music_id >=", value, "musicId");
            return (Criteria) this;
        }

        public Criteria andMusicIdLessThan(String value) {
            addCriterion("music_id <", value, "musicId");
            return (Criteria) this;
        }

        public Criteria andMusicIdLessThanOrEqualTo(String value) {
            addCriterion("music_id <=", value, "musicId");
            return (Criteria) this;
        }

        public Criteria andMusicIdLike(String value) {
            addCriterion("music_id like", value, "musicId");
            return (Criteria) this;
        }

        public Criteria andMusicIdNotLike(String value) {
            addCriterion("music_id not like", value, "musicId");
            return (Criteria) this;
        }

        public Criteria andMusicIdIn(List<String> values) {
            addCriterion("music_id in", values, "musicId");
            return (Criteria) this;
        }

        public Criteria andMusicIdNotIn(List<String> values) {
            addCriterion("music_id not in", values, "musicId");
            return (Criteria) this;
        }

        public Criteria andMusicIdBetween(String value1, String value2) {
            addCriterion("music_id between", value1, value2, "musicId");
            return (Criteria) this;
        }

        public Criteria andMusicIdNotBetween(String value1, String value2) {
            addCriterion("music_id not between", value1, value2, "musicId");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Short value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Short value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Short value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Short value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Short value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Short value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Short> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Short> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Short value1, Short value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Short value1, Short value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andMusicUrlIsNull() {
            addCriterion("music_url is null");
            return (Criteria) this;
        }

        public Criteria andMusicUrlIsNotNull() {
            addCriterion("music_url is not null");
            return (Criteria) this;
        }

        public Criteria andMusicUrlEqualTo(String value) {
            addCriterion("music_url =", value, "musicUrl");
            return (Criteria) this;
        }

        public Criteria andMusicUrlNotEqualTo(String value) {
            addCriterion("music_url <>", value, "musicUrl");
            return (Criteria) this;
        }

        public Criteria andMusicUrlGreaterThan(String value) {
            addCriterion("music_url >", value, "musicUrl");
            return (Criteria) this;
        }

        public Criteria andMusicUrlGreaterThanOrEqualTo(String value) {
            addCriterion("music_url >=", value, "musicUrl");
            return (Criteria) this;
        }

        public Criteria andMusicUrlLessThan(String value) {
            addCriterion("music_url <", value, "musicUrl");
            return (Criteria) this;
        }

        public Criteria andMusicUrlLessThanOrEqualTo(String value) {
            addCriterion("music_url <=", value, "musicUrl");
            return (Criteria) this;
        }

        public Criteria andMusicUrlLike(String value) {
            addCriterion("music_url like", value, "musicUrl");
            return (Criteria) this;
        }

        public Criteria andMusicUrlNotLike(String value) {
            addCriterion("music_url not like", value, "musicUrl");
            return (Criteria) this;
        }

        public Criteria andMusicUrlIn(List<String> values) {
            addCriterion("music_url in", values, "musicUrl");
            return (Criteria) this;
        }

        public Criteria andMusicUrlNotIn(List<String> values) {
            addCriterion("music_url not in", values, "musicUrl");
            return (Criteria) this;
        }

        public Criteria andMusicUrlBetween(String value1, String value2) {
            addCriterion("music_url between", value1, value2, "musicUrl");
            return (Criteria) this;
        }

        public Criteria andMusicUrlNotBetween(String value1, String value2) {
            addCriterion("music_url not between", value1, value2, "musicUrl");
            return (Criteria) this;
        }

        public Criteria andMusicNewUrlIsNull() {
            addCriterion("music_new_url is null");
            return (Criteria) this;
        }

        public Criteria andMusicNewUrlIsNotNull() {
            addCriterion("music_new_url is not null");
            return (Criteria) this;
        }

        public Criteria andMusicNewUrlEqualTo(String value) {
            addCriterion("music_new_url =", value, "musicNewUrl");
            return (Criteria) this;
        }

        public Criteria andMusicNewUrlNotEqualTo(String value) {
            addCriterion("music_new_url <>", value, "musicNewUrl");
            return (Criteria) this;
        }

        public Criteria andMusicNewUrlGreaterThan(String value) {
            addCriterion("music_new_url >", value, "musicNewUrl");
            return (Criteria) this;
        }

        public Criteria andMusicNewUrlGreaterThanOrEqualTo(String value) {
            addCriterion("music_new_url >=", value, "musicNewUrl");
            return (Criteria) this;
        }

        public Criteria andMusicNewUrlLessThan(String value) {
            addCriterion("music_new_url <", value, "musicNewUrl");
            return (Criteria) this;
        }

        public Criteria andMusicNewUrlLessThanOrEqualTo(String value) {
            addCriterion("music_new_url <=", value, "musicNewUrl");
            return (Criteria) this;
        }

        public Criteria andMusicNewUrlLike(String value) {
            addCriterion("music_new_url like", value, "musicNewUrl");
            return (Criteria) this;
        }

        public Criteria andMusicNewUrlNotLike(String value) {
            addCriterion("music_new_url not like", value, "musicNewUrl");
            return (Criteria) this;
        }

        public Criteria andMusicNewUrlIn(List<String> values) {
            addCriterion("music_new_url in", values, "musicNewUrl");
            return (Criteria) this;
        }

        public Criteria andMusicNewUrlNotIn(List<String> values) {
            addCriterion("music_new_url not in", values, "musicNewUrl");
            return (Criteria) this;
        }

        public Criteria andMusicNewUrlBetween(String value1, String value2) {
            addCriterion("music_new_url between", value1, value2, "musicNewUrl");
            return (Criteria) this;
        }

        public Criteria andMusicNewUrlNotBetween(String value1, String value2) {
            addCriterion("music_new_url not between", value1, value2, "musicNewUrl");
            return (Criteria) this;
        }

        public Criteria andMusicNameIsNull() {
            addCriterion("music_name is null");
            return (Criteria) this;
        }

        public Criteria andMusicNameIsNotNull() {
            addCriterion("music_name is not null");
            return (Criteria) this;
        }

        public Criteria andMusicNameEqualTo(String value) {
            addCriterion("music_name =", value, "musicName");
            return (Criteria) this;
        }

        public Criteria andMusicNameNotEqualTo(String value) {
            addCriterion("music_name <>", value, "musicName");
            return (Criteria) this;
        }

        public Criteria andMusicNameGreaterThan(String value) {
            addCriterion("music_name >", value, "musicName");
            return (Criteria) this;
        }

        public Criteria andMusicNameGreaterThanOrEqualTo(String value) {
            addCriterion("music_name >=", value, "musicName");
            return (Criteria) this;
        }

        public Criteria andMusicNameLessThan(String value) {
            addCriterion("music_name <", value, "musicName");
            return (Criteria) this;
        }

        public Criteria andMusicNameLessThanOrEqualTo(String value) {
            addCriterion("music_name <=", value, "musicName");
            return (Criteria) this;
        }

        public Criteria andMusicNameLike(String value) {
            addCriterion("music_name like", value, "musicName");
            return (Criteria) this;
        }

        public Criteria andMusicNameNotLike(String value) {
            addCriterion("music_name not like", value, "musicName");
            return (Criteria) this;
        }

        public Criteria andMusicNameIn(List<String> values) {
            addCriterion("music_name in", values, "musicName");
            return (Criteria) this;
        }

        public Criteria andMusicNameNotIn(List<String> values) {
            addCriterion("music_name not in", values, "musicName");
            return (Criteria) this;
        }

        public Criteria andMusicNameBetween(String value1, String value2) {
            addCriterion("music_name between", value1, value2, "musicName");
            return (Criteria) this;
        }

        public Criteria andMusicNameNotBetween(String value1, String value2) {
            addCriterion("music_name not between", value1, value2, "musicName");
            return (Criteria) this;
        }

        public Criteria andMusicTimeIsNull() {
            addCriterion("music_time is null");
            return (Criteria) this;
        }

        public Criteria andMusicTimeIsNotNull() {
            addCriterion("music_time is not null");
            return (Criteria) this;
        }

        public Criteria andMusicTimeEqualTo(Short value) {
            addCriterion("music_time =", value, "musicTime");
            return (Criteria) this;
        }

        public Criteria andMusicTimeNotEqualTo(Short value) {
            addCriterion("music_time <>", value, "musicTime");
            return (Criteria) this;
        }

        public Criteria andMusicTimeGreaterThan(Short value) {
            addCriterion("music_time >", value, "musicTime");
            return (Criteria) this;
        }

        public Criteria andMusicTimeGreaterThanOrEqualTo(Short value) {
            addCriterion("music_time >=", value, "musicTime");
            return (Criteria) this;
        }

        public Criteria andMusicTimeLessThan(Short value) {
            addCriterion("music_time <", value, "musicTime");
            return (Criteria) this;
        }

        public Criteria andMusicTimeLessThanOrEqualTo(Short value) {
            addCriterion("music_time <=", value, "musicTime");
            return (Criteria) this;
        }

        public Criteria andMusicTimeIn(List<Short> values) {
            addCriterion("music_time in", values, "musicTime");
            return (Criteria) this;
        }

        public Criteria andMusicTimeNotIn(List<Short> values) {
            addCriterion("music_time not in", values, "musicTime");
            return (Criteria) this;
        }

        public Criteria andMusicTimeBetween(Short value1, Short value2) {
            addCriterion("music_time between", value1, value2, "musicTime");
            return (Criteria) this;
        }

        public Criteria andMusicTimeNotBetween(Short value1, Short value2) {
            addCriterion("music_time not between", value1, value2, "musicTime");
            return (Criteria) this;
        }

        public Criteria andMusicSingerIsNull() {
            addCriterion("music_singer is null");
            return (Criteria) this;
        }

        public Criteria andMusicSingerIsNotNull() {
            addCriterion("music_singer is not null");
            return (Criteria) this;
        }

        public Criteria andMusicSingerEqualTo(String value) {
            addCriterion("music_singer =", value, "musicSinger");
            return (Criteria) this;
        }

        public Criteria andMusicSingerNotEqualTo(String value) {
            addCriterion("music_singer <>", value, "musicSinger");
            return (Criteria) this;
        }

        public Criteria andMusicSingerGreaterThan(String value) {
            addCriterion("music_singer >", value, "musicSinger");
            return (Criteria) this;
        }

        public Criteria andMusicSingerGreaterThanOrEqualTo(String value) {
            addCriterion("music_singer >=", value, "musicSinger");
            return (Criteria) this;
        }

        public Criteria andMusicSingerLessThan(String value) {
            addCriterion("music_singer <", value, "musicSinger");
            return (Criteria) this;
        }

        public Criteria andMusicSingerLessThanOrEqualTo(String value) {
            addCriterion("music_singer <=", value, "musicSinger");
            return (Criteria) this;
        }

        public Criteria andMusicSingerLike(String value) {
            addCriterion("music_singer like", value, "musicSinger");
            return (Criteria) this;
        }

        public Criteria andMusicSingerNotLike(String value) {
            addCriterion("music_singer not like", value, "musicSinger");
            return (Criteria) this;
        }

        public Criteria andMusicSingerIn(List<String> values) {
            addCriterion("music_singer in", values, "musicSinger");
            return (Criteria) this;
        }

        public Criteria andMusicSingerNotIn(List<String> values) {
            addCriterion("music_singer not in", values, "musicSinger");
            return (Criteria) this;
        }

        public Criteria andMusicSingerBetween(String value1, String value2) {
            addCriterion("music_singer between", value1, value2, "musicSinger");
            return (Criteria) this;
        }

        public Criteria andMusicSingerNotBetween(String value1, String value2) {
            addCriterion("music_singer not between", value1, value2, "musicSinger");
            return (Criteria) this;
        }

        public Criteria andMusicAlbumIsNull() {
            addCriterion("music_album is null");
            return (Criteria) this;
        }

        public Criteria andMusicAlbumIsNotNull() {
            addCriterion("music_album is not null");
            return (Criteria) this;
        }

        public Criteria andMusicAlbumEqualTo(String value) {
            addCriterion("music_album =", value, "musicAlbum");
            return (Criteria) this;
        }

        public Criteria andMusicAlbumNotEqualTo(String value) {
            addCriterion("music_album <>", value, "musicAlbum");
            return (Criteria) this;
        }

        public Criteria andMusicAlbumGreaterThan(String value) {
            addCriterion("music_album >", value, "musicAlbum");
            return (Criteria) this;
        }

        public Criteria andMusicAlbumGreaterThanOrEqualTo(String value) {
            addCriterion("music_album >=", value, "musicAlbum");
            return (Criteria) this;
        }

        public Criteria andMusicAlbumLessThan(String value) {
            addCriterion("music_album <", value, "musicAlbum");
            return (Criteria) this;
        }

        public Criteria andMusicAlbumLessThanOrEqualTo(String value) {
            addCriterion("music_album <=", value, "musicAlbum");
            return (Criteria) this;
        }

        public Criteria andMusicAlbumLike(String value) {
            addCriterion("music_album like", value, "musicAlbum");
            return (Criteria) this;
        }

        public Criteria andMusicAlbumNotLike(String value) {
            addCriterion("music_album not like", value, "musicAlbum");
            return (Criteria) this;
        }

        public Criteria andMusicAlbumIn(List<String> values) {
            addCriterion("music_album in", values, "musicAlbum");
            return (Criteria) this;
        }

        public Criteria andMusicAlbumNotIn(List<String> values) {
            addCriterion("music_album not in", values, "musicAlbum");
            return (Criteria) this;
        }

        public Criteria andMusicAlbumBetween(String value1, String value2) {
            addCriterion("music_album between", value1, value2, "musicAlbum");
            return (Criteria) this;
        }

        public Criteria andMusicAlbumNotBetween(String value1, String value2) {
            addCriterion("music_album not between", value1, value2, "musicAlbum");
            return (Criteria) this;
        }

        public Criteria andMusicUpdateIsNull() {
            addCriterion("music_update is null");
            return (Criteria) this;
        }

        public Criteria andMusicUpdateIsNotNull() {
            addCriterion("music_update is not null");
            return (Criteria) this;
        }

        public Criteria andMusicUpdateEqualTo(Date value) {
            addCriterion("music_update =", value, "musicUpdate");
            return (Criteria) this;
        }

        public Criteria andMusicUpdateNotEqualTo(Date value) {
            addCriterion("music_update <>", value, "musicUpdate");
            return (Criteria) this;
        }

        public Criteria andMusicUpdateGreaterThan(Date value) {
            addCriterion("music_update >", value, "musicUpdate");
            return (Criteria) this;
        }

        public Criteria andMusicUpdateGreaterThanOrEqualTo(Date value) {
            addCriterion("music_update >=", value, "musicUpdate");
            return (Criteria) this;
        }

        public Criteria andMusicUpdateLessThan(Date value) {
            addCriterion("music_update <", value, "musicUpdate");
            return (Criteria) this;
        }

        public Criteria andMusicUpdateLessThanOrEqualTo(Date value) {
            addCriterion("music_update <=", value, "musicUpdate");
            return (Criteria) this;
        }

        public Criteria andMusicUpdateIn(List<Date> values) {
            addCriterion("music_update in", values, "musicUpdate");
            return (Criteria) this;
        }

        public Criteria andMusicUpdateNotIn(List<Date> values) {
            addCriterion("music_update not in", values, "musicUpdate");
            return (Criteria) this;
        }

        public Criteria andMusicUpdateBetween(Date value1, Date value2) {
            addCriterion("music_update between", value1, value2, "musicUpdate");
            return (Criteria) this;
        }

        public Criteria andMusicUpdateNotBetween(Date value1, Date value2) {
            addCriterion("music_update not between", value1, value2, "musicUpdate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_music
     *
     * @mbg.generated do_not_delete_during_merge Mon Jul 01 10:36:07 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_music
     *
     * @mbg.generated Mon Jul 01 10:36:07 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}