package com.wyyuand.domain;

public class MusicChun {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_music_chun.music_id
     *
     * @mbg.generated Tue Jun 25 08:28:10 CST 2019
     */
    private String musicId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_music_chun.music_url
     *
     * @mbg.generated Tue Jun 25 08:28:10 CST 2019
     */
    private String musicUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_music_chun.music_id
     *
     * @return the value of t_music_chun.music_id
     *
     * @mbg.generated Tue Jun 25 08:28:10 CST 2019
     */
    public String getMusicId() {
        return musicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_music_chun.music_id
     *
     * @param musicId the value for t_music_chun.music_id
     *
     * @mbg.generated Tue Jun 25 08:28:10 CST 2019
     */
    public void setMusicId(String musicId) {
        this.musicId = musicId == null ? null : musicId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_music_chun.music_url
     *
     * @return the value of t_music_chun.music_url
     *
     * @mbg.generated Tue Jun 25 08:28:10 CST 2019
     */
    public String getMusicUrl() {
        return musicUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_music_chun.music_url
     *
     * @param musicUrl the value for t_music_chun.music_url
     *
     * @mbg.generated Tue Jun 25 08:28:10 CST 2019
     */
    public void setMusicUrl(String musicUrl) {
        this.musicUrl = musicUrl == null ? null : musicUrl.trim();
    }
}