package com.wyyuand.domain;

import java.util.ArrayList;
import java.util.List;

public class MusicChunExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_music_chun
     *
     * @mbg.generated Tue Jun 25 08:28:10 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_music_chun
     *
     * @mbg.generated Tue Jun 25 08:28:10 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_music_chun
     *
     * @mbg.generated Tue Jun 25 08:28:10 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_music_chun
     *
     * @mbg.generated Tue Jun 25 08:28:10 CST 2019
     */
    public MusicChunExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_music_chun
     *
     * @mbg.generated Tue Jun 25 08:28:10 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_music_chun
     *
     * @mbg.generated Tue Jun 25 08:28:10 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_music_chun
     *
     * @mbg.generated Tue Jun 25 08:28:10 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_music_chun
     *
     * @mbg.generated Tue Jun 25 08:28:10 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_music_chun
     *
     * @mbg.generated Tue Jun 25 08:28:10 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_music_chun
     *
     * @mbg.generated Tue Jun 25 08:28:10 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_music_chun
     *
     * @mbg.generated Tue Jun 25 08:28:10 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_music_chun
     *
     * @mbg.generated Tue Jun 25 08:28:10 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_music_chun
     *
     * @mbg.generated Tue Jun 25 08:28:10 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_music_chun
     *
     * @mbg.generated Tue Jun 25 08:28:10 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_music_chun
     *
     * @mbg.generated Tue Jun 25 08:28:10 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMusicIdIsNull() {
            addCriterion("music_id is null");
            return (Criteria) this;
        }

        public Criteria andMusicIdIsNotNull() {
            addCriterion("music_id is not null");
            return (Criteria) this;
        }

        public Criteria andMusicIdEqualTo(String value) {
            addCriterion("music_id =", value, "musicId");
            return (Criteria) this;
        }

        public Criteria andMusicIdNotEqualTo(String value) {
            addCriterion("music_id <>", value, "musicId");
            return (Criteria) this;
        }

        public Criteria andMusicIdGreaterThan(String value) {
            addCriterion("music_id >", value, "musicId");
            return (Criteria) this;
        }

        public Criteria andMusicIdGreaterThanOrEqualTo(String value) {
            addCriterion("music_id >=", value, "musicId");
            return (Criteria) this;
        }

        public Criteria andMusicIdLessThan(String value) {
            addCriterion("music_id <", value, "musicId");
            return (Criteria) this;
        }

        public Criteria andMusicIdLessThanOrEqualTo(String value) {
            addCriterion("music_id <=", value, "musicId");
            return (Criteria) this;
        }

        public Criteria andMusicIdLike(String value) {
            addCriterion("music_id like", value, "musicId");
            return (Criteria) this;
        }

        public Criteria andMusicIdNotLike(String value) {
            addCriterion("music_id not like", value, "musicId");
            return (Criteria) this;
        }

        public Criteria andMusicIdIn(List<String> values) {
            addCriterion("music_id in", values, "musicId");
            return (Criteria) this;
        }

        public Criteria andMusicIdNotIn(List<String> values) {
            addCriterion("music_id not in", values, "musicId");
            return (Criteria) this;
        }

        public Criteria andMusicIdBetween(String value1, String value2) {
            addCriterion("music_id between", value1, value2, "musicId");
            return (Criteria) this;
        }

        public Criteria andMusicIdNotBetween(String value1, String value2) {
            addCriterion("music_id not between", value1, value2, "musicId");
            return (Criteria) this;
        }

        public Criteria andMusicUrlIsNull() {
            addCriterion("music_url is null");
            return (Criteria) this;
        }

        public Criteria andMusicUrlIsNotNull() {
            addCriterion("music_url is not null");
            return (Criteria) this;
        }

        public Criteria andMusicUrlEqualTo(String value) {
            addCriterion("music_url =", value, "musicUrl");
            return (Criteria) this;
        }

        public Criteria andMusicUrlNotEqualTo(String value) {
            addCriterion("music_url <>", value, "musicUrl");
            return (Criteria) this;
        }

        public Criteria andMusicUrlGreaterThan(String value) {
            addCriterion("music_url >", value, "musicUrl");
            return (Criteria) this;
        }

        public Criteria andMusicUrlGreaterThanOrEqualTo(String value) {
            addCriterion("music_url >=", value, "musicUrl");
            return (Criteria) this;
        }

        public Criteria andMusicUrlLessThan(String value) {
            addCriterion("music_url <", value, "musicUrl");
            return (Criteria) this;
        }

        public Criteria andMusicUrlLessThanOrEqualTo(String value) {
            addCriterion("music_url <=", value, "musicUrl");
            return (Criteria) this;
        }

        public Criteria andMusicUrlLike(String value) {
            addCriterion("music_url like", value, "musicUrl");
            return (Criteria) this;
        }

        public Criteria andMusicUrlNotLike(String value) {
            addCriterion("music_url not like", value, "musicUrl");
            return (Criteria) this;
        }

        public Criteria andMusicUrlIn(List<String> values) {
            addCriterion("music_url in", values, "musicUrl");
            return (Criteria) this;
        }

        public Criteria andMusicUrlNotIn(List<String> values) {
            addCriterion("music_url not in", values, "musicUrl");
            return (Criteria) this;
        }

        public Criteria andMusicUrlBetween(String value1, String value2) {
            addCriterion("music_url between", value1, value2, "musicUrl");
            return (Criteria) this;
        }

        public Criteria andMusicUrlNotBetween(String value1, String value2) {
            addCriterion("music_url not between", value1, value2, "musicUrl");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_music_chun
     *
     * @mbg.generated do_not_delete_during_merge Tue Jun 25 08:28:10 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_music_chun
     *
     * @mbg.generated Tue Jun 25 08:28:10 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}