package com.wyyuand.domain;

import java.math.BigDecimal;

public class Prestatus {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_prestatus.id
     *
     * @mbg.generated Fri Jun 28 09:41:43 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_prestatus.period
     *
     * @mbg.generated Fri Jun 28 09:41:43 CST 2019
     */
    private String period;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_prestatus.picture
     *
     * @mbg.generated Fri Jun 28 09:41:43 CST 2019
     */
    private String picture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_prestatus.weight
     *
     * @mbg.generated Fri Jun 28 09:41:43 CST 2019
     */
    private BigDecimal weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_prestatus.len
     *
     * @mbg.generated Fri Jun 28 09:41:43 CST 2019
     */
    private BigDecimal len;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_prestatus.baby_say
     *
     * @mbg.generated Fri Jun 28 09:41:43 CST 2019
     */
    private String babySay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_prestatus.mom_say
     *
     * @mbg.generated Fri Jun 28 09:41:43 CST 2019
     */
    private String momSay;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_prestatus.id
     *
     * @return the value of t_prestatus.id
     *
     * @mbg.generated Fri Jun 28 09:41:43 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_prestatus.id
     *
     * @param id the value for t_prestatus.id
     *
     * @mbg.generated Fri Jun 28 09:41:43 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_prestatus.period
     *
     * @return the value of t_prestatus.period
     *
     * @mbg.generated Fri Jun 28 09:41:43 CST 2019
     */
    public String getPeriod() {
        return period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_prestatus.period
     *
     * @param period the value for t_prestatus.period
     *
     * @mbg.generated Fri Jun 28 09:41:43 CST 2019
     */
    public void setPeriod(String period) {
        this.period = period == null ? null : period.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_prestatus.picture
     *
     * @return the value of t_prestatus.picture
     *
     * @mbg.generated Fri Jun 28 09:41:43 CST 2019
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_prestatus.picture
     *
     * @param picture the value for t_prestatus.picture
     *
     * @mbg.generated Fri Jun 28 09:41:43 CST 2019
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_prestatus.weight
     *
     * @return the value of t_prestatus.weight
     *
     * @mbg.generated Fri Jun 28 09:41:43 CST 2019
     */
    public BigDecimal getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_prestatus.weight
     *
     * @param weight the value for t_prestatus.weight
     *
     * @mbg.generated Fri Jun 28 09:41:43 CST 2019
     */
    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_prestatus.len
     *
     * @return the value of t_prestatus.len
     *
     * @mbg.generated Fri Jun 28 09:41:43 CST 2019
     */
    public BigDecimal getLen() {
        return len;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_prestatus.len
     *
     * @param len the value for t_prestatus.len
     *
     * @mbg.generated Fri Jun 28 09:41:43 CST 2019
     */
    public void setLen(BigDecimal len) {
        this.len = len;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_prestatus.baby_say
     *
     * @return the value of t_prestatus.baby_say
     *
     * @mbg.generated Fri Jun 28 09:41:43 CST 2019
     */
    public String getBabySay() {
        return babySay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_prestatus.baby_say
     *
     * @param babySay the value for t_prestatus.baby_say
     *
     * @mbg.generated Fri Jun 28 09:41:43 CST 2019
     */
    public void setBabySay(String babySay) {
        this.babySay = babySay == null ? null : babySay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_prestatus.mom_say
     *
     * @return the value of t_prestatus.mom_say
     *
     * @mbg.generated Fri Jun 28 09:41:43 CST 2019
     */
    public String getMomSay() {
        return momSay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_prestatus.mom_say
     *
     * @param momSay the value for t_prestatus.mom_say
     *
     * @mbg.generated Fri Jun 28 09:41:43 CST 2019
     */
    public void setMomSay(String momSay) {
        this.momSay = momSay == null ? null : momSay.trim();
    }
}