package com.wyyuand.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class PreTimeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_pre_time
     *
     * @mbg.generated Wed Jul 03 10:07:01 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_pre_time
     *
     * @mbg.generated Wed Jul 03 10:07:01 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_pre_time
     *
     * @mbg.generated Wed Jul 03 10:07:01 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pre_time
     *
     * @mbg.generated Wed Jul 03 10:07:01 CST 2019
     */
    public PreTimeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pre_time
     *
     * @mbg.generated Wed Jul 03 10:07:01 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pre_time
     *
     * @mbg.generated Wed Jul 03 10:07:01 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pre_time
     *
     * @mbg.generated Wed Jul 03 10:07:01 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pre_time
     *
     * @mbg.generated Wed Jul 03 10:07:01 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pre_time
     *
     * @mbg.generated Wed Jul 03 10:07:01 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pre_time
     *
     * @mbg.generated Wed Jul 03 10:07:01 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pre_time
     *
     * @mbg.generated Wed Jul 03 10:07:01 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pre_time
     *
     * @mbg.generated Wed Jul 03 10:07:01 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pre_time
     *
     * @mbg.generated Wed Jul 03 10:07:01 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pre_time
     *
     * @mbg.generated Wed Jul 03 10:07:01 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_pre_time
     *
     * @mbg.generated Wed Jul 03 10:07:01 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andCheckIdIsNull() {
            addCriterion("check_id is null");
            return (Criteria) this;
        }

        public Criteria andCheckIdIsNotNull() {
            addCriterion("check_id is not null");
            return (Criteria) this;
        }

        public Criteria andCheckIdEqualTo(String value) {
            addCriterion("check_id =", value, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckIdNotEqualTo(String value) {
            addCriterion("check_id <>", value, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckIdGreaterThan(String value) {
            addCriterion("check_id >", value, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckIdGreaterThanOrEqualTo(String value) {
            addCriterion("check_id >=", value, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckIdLessThan(String value) {
            addCriterion("check_id <", value, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckIdLessThanOrEqualTo(String value) {
            addCriterion("check_id <=", value, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckIdLike(String value) {
            addCriterion("check_id like", value, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckIdNotLike(String value) {
            addCriterion("check_id not like", value, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckIdIn(List<String> values) {
            addCriterion("check_id in", values, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckIdNotIn(List<String> values) {
            addCriterion("check_id not in", values, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckIdBetween(String value1, String value2) {
            addCriterion("check_id between", value1, value2, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckIdNotBetween(String value1, String value2) {
            addCriterion("check_id not between", value1, value2, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckPreIsNull() {
            addCriterion("check_pre is null");
            return (Criteria) this;
        }

        public Criteria andCheckPreIsNotNull() {
            addCriterion("check_pre is not null");
            return (Criteria) this;
        }

        public Criteria andCheckPreEqualTo(String value) {
            addCriterion("check_pre =", value, "checkPre");
            return (Criteria) this;
        }

        public Criteria andCheckPreNotEqualTo(String value) {
            addCriterion("check_pre <>", value, "checkPre");
            return (Criteria) this;
        }

        public Criteria andCheckPreGreaterThan(String value) {
            addCriterion("check_pre >", value, "checkPre");
            return (Criteria) this;
        }

        public Criteria andCheckPreGreaterThanOrEqualTo(String value) {
            addCriterion("check_pre >=", value, "checkPre");
            return (Criteria) this;
        }

        public Criteria andCheckPreLessThan(String value) {
            addCriterion("check_pre <", value, "checkPre");
            return (Criteria) this;
        }

        public Criteria andCheckPreLessThanOrEqualTo(String value) {
            addCriterion("check_pre <=", value, "checkPre");
            return (Criteria) this;
        }

        public Criteria andCheckPreLike(String value) {
            addCriterion("check_pre like", value, "checkPre");
            return (Criteria) this;
        }

        public Criteria andCheckPreNotLike(String value) {
            addCriterion("check_pre not like", value, "checkPre");
            return (Criteria) this;
        }

        public Criteria andCheckPreIn(List<String> values) {
            addCriterion("check_pre in", values, "checkPre");
            return (Criteria) this;
        }

        public Criteria andCheckPreNotIn(List<String> values) {
            addCriterion("check_pre not in", values, "checkPre");
            return (Criteria) this;
        }

        public Criteria andCheckPreBetween(String value1, String value2) {
            addCriterion("check_pre between", value1, value2, "checkPre");
            return (Criteria) this;
        }

        public Criteria andCheckPreNotBetween(String value1, String value2) {
            addCriterion("check_pre not between", value1, value2, "checkPre");
            return (Criteria) this;
        }

        public Criteria andCheckSecondIsNull() {
            addCriterion("check_second is null");
            return (Criteria) this;
        }

        public Criteria andCheckSecondIsNotNull() {
            addCriterion("check_second is not null");
            return (Criteria) this;
        }

        public Criteria andCheckSecondEqualTo(String value) {
            addCriterion("check_second =", value, "checkSecond");
            return (Criteria) this;
        }

        public Criteria andCheckSecondNotEqualTo(String value) {
            addCriterion("check_second <>", value, "checkSecond");
            return (Criteria) this;
        }

        public Criteria andCheckSecondGreaterThan(String value) {
            addCriterion("check_second >", value, "checkSecond");
            return (Criteria) this;
        }

        public Criteria andCheckSecondGreaterThanOrEqualTo(String value) {
            addCriterion("check_second >=", value, "checkSecond");
            return (Criteria) this;
        }

        public Criteria andCheckSecondLessThan(String value) {
            addCriterion("check_second <", value, "checkSecond");
            return (Criteria) this;
        }

        public Criteria andCheckSecondLessThanOrEqualTo(String value) {
            addCriterion("check_second <=", value, "checkSecond");
            return (Criteria) this;
        }

        public Criteria andCheckSecondLike(String value) {
            addCriterion("check_second like", value, "checkSecond");
            return (Criteria) this;
        }

        public Criteria andCheckSecondNotLike(String value) {
            addCriterion("check_second not like", value, "checkSecond");
            return (Criteria) this;
        }

        public Criteria andCheckSecondIn(List<String> values) {
            addCriterion("check_second in", values, "checkSecond");
            return (Criteria) this;
        }

        public Criteria andCheckSecondNotIn(List<String> values) {
            addCriterion("check_second not in", values, "checkSecond");
            return (Criteria) this;
        }

        public Criteria andCheckSecondBetween(String value1, String value2) {
            addCriterion("check_second between", value1, value2, "checkSecond");
            return (Criteria) this;
        }

        public Criteria andCheckSecondNotBetween(String value1, String value2) {
            addCriterion("check_second not between", value1, value2, "checkSecond");
            return (Criteria) this;
        }

        public Criteria andCheckUsuIsNull() {
            addCriterion("check_usu is null");
            return (Criteria) this;
        }

        public Criteria andCheckUsuIsNotNull() {
            addCriterion("check_usu is not null");
            return (Criteria) this;
        }

        public Criteria andCheckUsuEqualTo(String value) {
            addCriterion("check_usu =", value, "checkUsu");
            return (Criteria) this;
        }

        public Criteria andCheckUsuNotEqualTo(String value) {
            addCriterion("check_usu <>", value, "checkUsu");
            return (Criteria) this;
        }

        public Criteria andCheckUsuGreaterThan(String value) {
            addCriterion("check_usu >", value, "checkUsu");
            return (Criteria) this;
        }

        public Criteria andCheckUsuGreaterThanOrEqualTo(String value) {
            addCriterion("check_usu >=", value, "checkUsu");
            return (Criteria) this;
        }

        public Criteria andCheckUsuLessThan(String value) {
            addCriterion("check_usu <", value, "checkUsu");
            return (Criteria) this;
        }

        public Criteria andCheckUsuLessThanOrEqualTo(String value) {
            addCriterion("check_usu <=", value, "checkUsu");
            return (Criteria) this;
        }

        public Criteria andCheckUsuLike(String value) {
            addCriterion("check_usu like", value, "checkUsu");
            return (Criteria) this;
        }

        public Criteria andCheckUsuNotLike(String value) {
            addCriterion("check_usu not like", value, "checkUsu");
            return (Criteria) this;
        }

        public Criteria andCheckUsuIn(List<String> values) {
            addCriterion("check_usu in", values, "checkUsu");
            return (Criteria) this;
        }

        public Criteria andCheckUsuNotIn(List<String> values) {
            addCriterion("check_usu not in", values, "checkUsu");
            return (Criteria) this;
        }

        public Criteria andCheckUsuBetween(String value1, String value2) {
            addCriterion("check_usu between", value1, value2, "checkUsu");
            return (Criteria) this;
        }

        public Criteria andCheckUsuNotBetween(String value1, String value2) {
            addCriterion("check_usu not between", value1, value2, "checkUsu");
            return (Criteria) this;
        }

        public Criteria andCheckKeyIsNull() {
            addCriterion("check_key is null");
            return (Criteria) this;
        }

        public Criteria andCheckKeyIsNotNull() {
            addCriterion("check_key is not null");
            return (Criteria) this;
        }

        public Criteria andCheckKeyEqualTo(String value) {
            addCriterion("check_key =", value, "checkKey");
            return (Criteria) this;
        }

        public Criteria andCheckKeyNotEqualTo(String value) {
            addCriterion("check_key <>", value, "checkKey");
            return (Criteria) this;
        }

        public Criteria andCheckKeyGreaterThan(String value) {
            addCriterion("check_key >", value, "checkKey");
            return (Criteria) this;
        }

        public Criteria andCheckKeyGreaterThanOrEqualTo(String value) {
            addCriterion("check_key >=", value, "checkKey");
            return (Criteria) this;
        }

        public Criteria andCheckKeyLessThan(String value) {
            addCriterion("check_key <", value, "checkKey");
            return (Criteria) this;
        }

        public Criteria andCheckKeyLessThanOrEqualTo(String value) {
            addCriterion("check_key <=", value, "checkKey");
            return (Criteria) this;
        }

        public Criteria andCheckKeyLike(String value) {
            addCriterion("check_key like", value, "checkKey");
            return (Criteria) this;
        }

        public Criteria andCheckKeyNotLike(String value) {
            addCriterion("check_key not like", value, "checkKey");
            return (Criteria) this;
        }

        public Criteria andCheckKeyIn(List<String> values) {
            addCriterion("check_key in", values, "checkKey");
            return (Criteria) this;
        }

        public Criteria andCheckKeyNotIn(List<String> values) {
            addCriterion("check_key not in", values, "checkKey");
            return (Criteria) this;
        }

        public Criteria andCheckKeyBetween(String value1, String value2) {
            addCriterion("check_key between", value1, value2, "checkKey");
            return (Criteria) this;
        }

        public Criteria andCheckKeyNotBetween(String value1, String value2) {
            addCriterion("check_key not between", value1, value2, "checkKey");
            return (Criteria) this;
        }

        public Criteria andCheckDateIsNull() {
            addCriterion("check_date is null");
            return (Criteria) this;
        }

        public Criteria andCheckDateIsNotNull() {
            addCriterion("check_date is not null");
            return (Criteria) this;
        }

        public Criteria andCheckDateEqualTo(Date value) {
            addCriterionForJDBCDate("check_date =", value, "checkDate");
            return (Criteria) this;
        }

        public Criteria andCheckDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("check_date <>", value, "checkDate");
            return (Criteria) this;
        }

        public Criteria andCheckDateGreaterThan(Date value) {
            addCriterionForJDBCDate("check_date >", value, "checkDate");
            return (Criteria) this;
        }

        public Criteria andCheckDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("check_date >=", value, "checkDate");
            return (Criteria) this;
        }

        public Criteria andCheckDateLessThan(Date value) {
            addCriterionForJDBCDate("check_date <", value, "checkDate");
            return (Criteria) this;
        }

        public Criteria andCheckDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("check_date <=", value, "checkDate");
            return (Criteria) this;
        }

        public Criteria andCheckDateIn(List<Date> values) {
            addCriterionForJDBCDate("check_date in", values, "checkDate");
            return (Criteria) this;
        }

        public Criteria andCheckDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("check_date not in", values, "checkDate");
            return (Criteria) this;
        }

        public Criteria andCheckDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("check_date between", value1, value2, "checkDate");
            return (Criteria) this;
        }

        public Criteria andCheckDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("check_date not between", value1, value2, "checkDate");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_pre_time
     *
     * @mbg.generated do_not_delete_during_merge Wed Jul 03 10:07:01 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_pre_time
     *
     * @mbg.generated Wed Jul 03 10:07:01 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}