package com.wyyuand.domain;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class PreTime {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pre_time.check_id
     *
     * @mbg.generated Wed Jul 03 10:07:01 CST 2019
     */
    private String checkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pre_time.check_pre
     *
     * @mbg.generated Wed Jul 03 10:07:01 CST 2019
     */
    private String checkPre;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pre_time.check_second
     *
     * @mbg.generated Wed Jul 03 10:07:01 CST 2019
     */
    private String checkSecond;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pre_time.check_usu
     *
     * @mbg.generated Wed Jul 03 10:07:01 CST 2019
     */
    private String checkUsu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pre_time.check_key
     *
     * @mbg.generated Wed Jul 03 10:07:01 CST 2019
     */
    private String checkKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pre_time.check_date
     *
     * @mbg.generated Wed Jul 03 10:07:01 CST 2019
     */
    private Date checkDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pre_time.status
     *
     * @mbg.generated Wed Jul 03 10:07:01 CST 2019
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pre_time.check_id
     *
     * @return the value of t_pre_time.check_id
     *
     * @mbg.generated Wed Jul 03 10:07:01 CST 2019
     */
    public String getCheckId() {
        return checkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pre_time.check_id
     *
     * @param checkId the value for t_pre_time.check_id
     *
     * @mbg.generated Wed Jul 03 10:07:01 CST 2019
     */
    public void setCheckId(String checkId) {
        this.checkId = checkId == null ? null : checkId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pre_time.check_pre
     *
     * @return the value of t_pre_time.check_pre
     *
     * @mbg.generated Wed Jul 03 10:07:01 CST 2019
     */
    public String getCheckPre() {
        return checkPre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pre_time.check_pre
     *
     * @param checkPre the value for t_pre_time.check_pre
     *
     * @mbg.generated Wed Jul 03 10:07:01 CST 2019
     */
    public void setCheckPre(String checkPre) {
        this.checkPre = checkPre == null ? null : checkPre.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pre_time.check_second
     *
     * @return the value of t_pre_time.check_second
     *
     * @mbg.generated Wed Jul 03 10:07:01 CST 2019
     */
    public String getCheckSecond() {
        return checkSecond;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pre_time.check_second
     *
     * @param checkSecond the value for t_pre_time.check_second
     *
     * @mbg.generated Wed Jul 03 10:07:01 CST 2019
     */
    public void setCheckSecond(String checkSecond) {
        this.checkSecond = checkSecond == null ? null : checkSecond.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pre_time.check_usu
     *
     * @return the value of t_pre_time.check_usu
     *
     * @mbg.generated Wed Jul 03 10:07:01 CST 2019
     */
    public String getCheckUsu() {
        return checkUsu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pre_time.check_usu
     *
     * @param checkUsu the value for t_pre_time.check_usu
     *
     * @mbg.generated Wed Jul 03 10:07:01 CST 2019
     */
    public void setCheckUsu(String checkUsu) {
        this.checkUsu = checkUsu == null ? null : checkUsu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pre_time.check_key
     *
     * @return the value of t_pre_time.check_key
     *
     * @mbg.generated Wed Jul 03 10:07:01 CST 2019
     */
    public String getCheckKey() {
        return checkKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pre_time.check_key
     *
     * @param checkKey the value for t_pre_time.check_key
     *
     * @mbg.generated Wed Jul 03 10:07:01 CST 2019
     */
    public void setCheckKey(String checkKey) {
        this.checkKey = checkKey == null ? null : checkKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pre_time.check_date
     *
     * @return the value of t_pre_time.check_date
     *
     * @mbg.generated Wed Jul 03 10:07:01 CST 2019
     */

    @DateTimeFormat(pattern="yyyy-MM-dd")
    @JsonFormat(pattern="yyyy-MM-dd",timezone = "GMT+8")
    public Date getCheckDate() {
        return checkDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pre_time.check_date
     *
     * @param checkDate the value for t_pre_time.check_date
     *
     * @mbg.generated Wed Jul 03 10:07:01 CST 2019
     */
    public void setCheckDate(Date checkDate) {
        this.checkDate = checkDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pre_time.status
     *
     * @return the value of t_pre_time.status
     *
     * @mbg.generated Wed Jul 03 10:07:01 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pre_time.status
     *
     * @param status the value for t_pre_time.status
     *
     * @mbg.generated Wed Jul 03 10:07:01 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}